### ISSUE TITLE
__unicode__ makes 400+ queries for translations. is there a way for prefetch_related ?

### ISSUE THREAD

**Issue by tunavargi** [KristianOellegaard/django-hvad#109]
I have the following model 

```
class HotelType(TranslatableModel):
    code = models.CharField(max_length=255, unique=True)
    translations = TranslatedFields(name=models.CharField(max_length=255))
    objects = HotelTypeManager()

    def __unicode__(self):
        return self.lazy_translation_getter('name')
```

When I ask for HotelList that have the HotelType in list_display in admin, makes 400 queries. Each time it goes and ask for translated field. Is there a way to apply prefetch_related ?

**Comment by spectras** [comment]
In case someone still care about this, you would now do:
```python
    # if you just want to limit the queryset to objects in current language
    qs = Country.objects.language()
    
    # if you want all objects, no matter the language
    qs = Country.objects.language().fallbacks()
```
Actually, objects that have no translation at all in any language will still be missing, you can get them separately using `Country.objects.untranslated().filter(translations=None)` if you really need to, but as a rule, you should avoid creating such objects. It is even possible that hvad will forbid it at some point.
