### ISSUE TITLE
Dumpdata not working for translated model

### ISSUE THREAD

**Issue by fivethreeo** [KristianOellegaard/django-hvad#133]
manage.py dumpdata hvad_blog

manage.py dumpdata hvad_blog.entrytranslation

Both gives:

CommandError: Unable to serialize database: 'NoneType' object has no attribute '_meta'

**Comment by kpy21ui** [comment]
Problem still occurred

**Comment by kpy21ui** [comment]
Models in which the manager is explicitly identified dumpdata not work

**Comment by spectras** [comment]
@kpy21ui Interesting. Thanks for taking the time to narrow it down. At least it's no longer a blind search, I'll have something to start searching from when I tackle this issue.
