### ISSUE TITLE
Querying all languages is not working (fixed...)

### ISSUE THREAD

**Issue by roodie** [KristianOellegaard/django-hvad#200]
Hey, I have a very simple model, nothing fancy:

``` python
class Program(TranslatableModel):
    translations = TranslatedFields(
        title = models.CharField(max_length=200),
        subtitle = models.CharField(max_length=200, blank=True, default=""),
        description = models.TextField(blank=True, default=''),
    )
```

Querying a specific language version is easy - but I have to get all the different versions with .language('all') for indexing purposes, and it is simply not working. No errors, no indicators, it just fails to return any rows. Any idea where should I start debugging the issue? Or am I missing something?

I've just opened a django shell and tried it:

```
>>> Program.objects.language('en').count()
9
>>> Program.objects.language('hu').count()
9
>>> Program.objects.language('all').count()
0
```

**Comment by kartikdanidhariya** [comment]
please tell me that how you get all languages objects from translated table.

**Comment by spectras** [comment]
Hello @kartikdanidhariya, could you please open a new ticket for your question?
