### ISSUE TITLE
Django Rest Framework and Django-Hvad

### ISSUE THREAD

**Issue by psychok7** [KristianOellegaard/django-hvad#211]
so i needed to add some model-translation support for my DRF API and i started using django-hvad.

It seems to work well with my django application but i am getting some issues with the DRF APi.

I am trying to create a simple POST request and i am getting a error:

`Accessing a translated field requires that the instance has a translation loaded, or a valid translation in current language (en) loadable from the database`

Here are my models, serializers and viewsets:

Model:

```
class Mission(TranslatableModel):
    translations = TranslatedFields(
        mission=models.CharField(max_length=255, help_text="Mission name"),
    )

    def __unicode__(self):
        return self.lazy_translation_getter('mission', str(self.pk))
```

Serializer:

```
class MissionSerializer(serializers.ModelSerializer):
    mission = serializers.CharField(source='mission')

    class Meta:
        model = Mission
```

Viewset:

```
class MissionViewSet(viewsets.ModelViewSet):
    queryset = Mission.objects.language().all()
    serializer_class = MissionSerializer
    authentication_classes = (NoAuthentication,)
    permission_classes = (AllowAny,)

    def get_queryset(self):
        # Set Language For Translations
        user_language = self.request.GET.get('language')
        if user_language:
            translation.activate(user_language)
        return Mission.objects.language().all()
```

Does anyone know how i can get around this??

**Comment by alfredrumss** [comment]
hi @spectras  

i have a similiar error but when I implement a filter class on my ViewSet:

class RestaurantViewSet(viewsets.ModelViewSet):
	queryset = Restaurant.objects.language().all()
	serializer_class = RestaurantSerializer
	permission_classes = (permissions.AllowAny, )
	filter_backends = (filters.DjangoFilterBackend,)
	filter_class = RestaurantFilters
	lookup_field = 'slug'
	pagination_class = StandardResultsSetPagination

	def get_queryset(self):
		user_language = self.request.GET.get('language')
		return Restaurant.objects.language(user_language).all().order_by('-created_at')

My filter class is:

class RestaurantFilters(FilterSet):
	category = CharFilter(name='category', lookup_expr='exact')

	class Meta:
		model = Restaurant
		fields = ['category']

**Comment by alfredrumss** [comment]
the error is 

FilterSet model <class 'restaurant.models.Restaurant'> does not match queryset model <class 'restaurant.models.RestaurantTranslation'>

@spectras
