### ISSUE TITLE
Issues with BaseTranslationFormSet

### ISSUE THREAD

**Issue by psychok7** [KristianOellegaard/django-hvad#227]
Hi there, so basically i add a bunch of untranslated models and i was using a `BaseInlineFormSet` in the admin for some validations. Everything worked fine.

I then converted this models to have translations using django-hvad, and replaced `BaseInlineFormSet` with `BaseTranslationFormSet`.  Now it seems like my cleaned method is not getting called for some reason.

```
class AnswerFormSet(BaseTranslationFormSet):
    def clean(self):
        super(AnswerFormSet, self).clean()

        check_if_answer_or_order = 0
        for form in self.forms:
            if not hasattr(form, 'cleaned_data'):
                continue

            if form.cleaned_data.get('correct_answer_or_order'):
                check_if_answer_or_order += 1

        if 1 <= check_if_answer_or_order <= 4:
            pass
        else:
            raise ValidationError('There must be at least 1 answer!')
```

and the admin.py

```
class AnswerInline(TranslatableStackedInline):
    model = Answer
    formset = AnswerFormSet
    min_num = max_num = 4


class QuizAdmin(TranslatableAdmin):
    readonly_fields = ('image_tag',)
    raw_id_fields = ('category',)
    inlines = [AnswerInline,]

admin.site.register(Quiz, QuizAdmin)
```

Any ideas what could be wrong??

**Comment by spectras** [comment]
Hello !

I think the issue comes from using `BaseTranslationFormSet`. This one is intended for making a formset of all translations of a single object. Here, it would be used to edit a single answer in all available languages.

What you seem to want here, is a regular formset, of translatable forms. That is, a formset in only one language, displaying language-aware forms. For displaying a formset of several answers, all of them in one language, you should stick with a regular inline formset, and make it work on a `TranslatableModelForm`. 

I am no expert on the admin submodule, but I believe here it should actually work out of the box if your custom formset inherits Django's `BaseInlineFormSet`? Have you tried it? How does it work (or not work)?

**Comment by psychok7** [comment]
@spectras when using a normal `BaseInlineFormSet` from django.forms nothing seems to happen (the formset i created is not even called i think).. i attach it by doing `formset = AnswerFormSet` in my `TranslatableStackedInline`.. so i have no idea what could be the issue

**Comment by spectras** [comment]
I did a quick test and I think I can reproduce your problem. It seems to stem out of formset being commented out in hvad's admin implementation. I'll have to understand why, but this initial test lean towards a bug.
I must go now, but I'll investigate, and hopefully fix it tonight.

**Comment by psychok7** [comment]
@spectras ok thanks, ill be waiting for your update ;)

**Comment by spectras** [comment]
Could you please test something:
Try to open `hvad/admin.py`, and uncomment line 401, `"formset": self.formset,`

It should then take your custom formset into account properly. It seems to work for me, and unfortunately it was commented out before the initial repo creation so I do not know why. So if it works, I will make a proper fix with test cases.

**Comment by psychok7** [comment]
@spectras it seems to be working if i uncomment the formset. basically i overriden `get_formset` in my apps `admin.py`

**Comment by psychok7** [comment]
By the way, it only works if i use `BaseInlineFormSet`

**Comment by spectras** [comment]
Alright, thanks, I think all that is needed is that un-commenting, and thorough testing.
It's normal you cannot use a `BaseTranslationFormSet` here, it serves a different purpose. But you should be able to use any custom formset as long as it inherits `BaseInlineFormSet`.
