### ISSUE TITLE
raw_id_fields in the admin not working for foreign key

### ISSUE THREAD

**Issue by psychok7** [KristianOellegaard/django-hvad#236]
Hey there, so i am trying to convert a `translatable foreign key` in the admin to a `raw_id_field` so i can have better performance, but i am getting this error `The value of 'raw_id_fields[0]' refers to 'image', which is not an attribute of 'core.WebsiteExhibitionGallery'.`

Its probably something silly but i cant seem to get around it.

admin.py

```
class WebsiteExhibitionGalleryAdmin(TranslatableAdmin):
    raw_id_fields = ('image',) # i also tried image__source_file with no luck
    readonly_fields = ('image_tag',)

admin.site.register(WebsiteExhibitionGallery, WebsiteExhibitionGalleryAdmin)
```

```
class WebsiteExhibitionGallery(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(
            max_length=200, blank=True, null=True,
            help_text="Exhibition Gallery title"
        ),
        image=models.OneToOneField(
            'core.Multimedia', blank=True, null=True,
            help_text="Exhibition Gallery Image",
            related_name='websiteexhibitiongalleries_images'
        ),
    )

    def __unicode__(self):
        return str(self.pk)
```

Any ideas how i can fix this??

**Comment by spectras** [comment]
Hello,
I don't know that much about the inner workings of Django's admin app, especially given how much is has changed over the last few months.
I guess you could try working around this with `translations__image`. It might just work, depending on what the admin app tries to do with the field. Please tell me what happens.

**Comment by psychok7** [comment]
@spectras no luck.... i tried all three:

`
raw_id_fields = ('translations__image',)
raw_id_fields = ('core_websiteexhibitiongallery_translation__image__source_file',)
raw_id_fields = ('core_websiteexhibitiongallery_translation__source_file',)
```

**Comment by spectras** [comment]
Bad luck. The admin part of hvad lacks a maintainer actually, and is in real need of updating and upgrading. I refactored every other piece of hvad over last year but, unfortunately, I have never used Django admin so I cannot really maintain it.

Especially, for your specific problem, it actually works, it's just that the admin app's validation method checks the contents of `raw_id_fields` and aborts your application. By manually bypassing this test in the debugger, I can make it pass and work properly. Hmmmmm

**Comment by psychok7** [comment]
@spectras i tried doing `search_fields = ['translations__text']` in a different problem and it worked. so maybe if you have an idea on what is the difference between the `search_fields` and the `raw_id_fields` then it might help towards the solution

**Comment by spectras** [comment]
Yeah, it's all in the validation process. It *would* work, but the admin application does more restrictive checks on `raw_id_fields`. It's a pity, because if I just comment out the checks in django, it works fine.

**Comment by spectras** [comment]
I updated #187, which tracks the main issue behind all admin options. I'll close this one so all "translated fields in admin options" issues and ideas are in one place.
