### ISSUE TITLE
Cannot show translatable model fields in Rest framework 3.1.1 (Django 1.8)

### ISSUE THREAD

**Issue by paolostefan** [KristianOellegaard/django-hvad#238]
The docs lack a working example of how to implement a viewset with translatable fields, or a TranslatableMixin.
The issue is detailed in this Stackoverflow question: http://stackoverflow.com/q/29554903/719247

**Comment by spectras** [comment]
Hello,
I am quite busy right now, I'll have a look in a few hours.

**Comment by spectras** [comment]
Hi again. So, I put your code into a blank project, did a couple of tests and it seems to be working fine.
I put a tarball there: http://www.filedropper.com/hvadtest. 
I can successfuly access /api/websites/, /api/websites/1/ and the same with prefixes.

Please tell me if I missed something, and whether it works for you. I used the environment specification from your stackoverflow post:
```
Django==1.8
django-hvad==1.2.0
djangorestframework==3.1.1
```
I'm running python 3.4, though I doubt that matters.
Also, could you post the full error you get, including stack trace?

**Comment by paolostefan** [comment]
Hi, thanks a lot for your effort and prompt answer.

I'm running Python 2.7.9, maybe it's part of the problem. The project is pretty big and runs on a Mac, but I tried to replicate only the relevant bits on a Windows machine and got the same error (using python 2.7.9). So maybe the two things are related.

**Detail info follows**

`pip freeze`outputs:
 
Django==1.8
django-allauth==0.19.1
django-countries-plus==0.3.3
django-filter==0.9.2
django-grappelli==2.6.3
django-guardian==1.2.5
django-hvad==1.2.0
django-languages-plus==0.1.5
django-social-auth==0.7.28
djangorestframework==3.0.5
easy-thumbnails==2.2
ecdsa==0.11
Fabric==1.10.1
html2text==2015.2.18
httplib2==0.9
Markdown==2.6.1
oauth2==1.5.211
oauthlib==0.7.2
paramiko==1.15.2
Pillow==2.7.0
psycopg2==2.5.4
pycrypto==2.6.1
PyJWT==0.4.1
python-openid==2.2.5
python-social-auth==0.2.1
requests==2.5.1
requests-oauthlib==0.4.2
six==1.9.0

The error page contains this message:

WrongManager at /it/api/v1/websites/
To access translated fields like 'url' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method.
Request Method:	GET
Request URL:	http://127.0.0.1:8000/it/api/v1/websites/
Django Version:	1.8
Exception Type:	WrongManager
Exception Value:	
To access translated fields like 'url' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method.
Exception Location:	/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/hvad/utils.py in __call__, line 139
Python Executable:	/Users/paolostefan/.virtualenvs/quaderno_s/bin/python
Python Version:	2.7.9
Python Path:	
['/Users/paolostefan/Sites/quaderno/quaderno_s',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python27.zip',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/plat-darwin',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/plat-mac',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/lib-tk',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/lib-old',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages']

**Full stack trace start**
-------
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/it/api/v1/websites/

Django Version: 1.8
Python Version: 2.7.9
Installed Applications:
('grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'countries_plus',
 'languages_plus',
 'rest_framework',
 'hvad',
 'easy_thumbnails',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.facebook',
 'allauth.socialaccount.providers.google',
 'skin',
 'scrittori',
 'contenuti',
 'tassonomia')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware')


Traceback:
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/viewsets.py" in view
  85.             return self.dispatch(request, *args, **kwargs)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  407.             response = self.handle_exception(exc)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  404.             response = handler(request, *args, **kwargs)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/mixins.py" in list
  46.         return Response(serializer.data)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/serializers.py" in data
  615.         ret = super(ListSerializer, self).data
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/serializers.py" in data
  212.                 self._data = self.to_representation(self.instance)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/serializers.py" in to_representation
  565.             self.child.to_representation(item) for item in iterable
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/serializers.py" in to_representation
  419.         fields = [field for field in self.fields.values() if not field.write_only]
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/serializers.py" in fields
  312.             for key, value in self.get_fields().items():
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/rest_framework/serializers.py" in get_fields
  940.                 model_field = model._meta.get_field(model_field_name)
File "/Users/paolostefan/.virtualenvs/quaderno_s/lib/python2.7/site-packages/hvad/utils.py" in __call__
  139.                                    "method." % name)

Exception Type: WrongManager at /it/api/v1/websites/
Exception Value: To access translated fields like 'url' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method.
----
**Full stack trace end**

**Comment by spectras** [comment]
Thanks.
Well, it seems your `pip freeze` output tells it is using REST framework 3.0 for some reason. The API hvad uses for interacting with REST framework was introduced in version 3.1.0.
Could you please double check the version of REST framework that is in use, and make sure it is at least 3.1.0?

**Comment by paolostefan** [comment]
You are right about the REST framework version: I had to upgrade it.
Apart from that, my code required a couple edits before actually working (thanks again for your working example! :) )

Now the situation is as follows:
1. I **still** cannot manage to use `TranslationMixin`s (the error is the same as above), I'm using the other way (the ViewSet having `Website.objects.language().all()` as queryset);
2. I don't get correctly what the untranslated API page `/api/v1/websites/` should show, and which fields it should ask for. Currently, it asks for translatable fields, and saves their content in the default language (`en`) and then redirects to that translation of the API, that is `/en/api/v1/websites/`.
 But, since my browser's preferred language is `it`, when I visit the "untranslated" API page, that is `/api/v1/websites/` instead of `/en/api/v1/websites/`, it shows only the records with an **Italian** translation (`/api/v1/websites/` and `/it/api/v1/websites/` show the same content).

**Comment by spectras** [comment]
For 1) I'll have a look a bit later.
For 2) that is the expected behavior. Namely, here is what happens:

* all pages of your API are translated (using a TranslatableModelSerializer means it is translation-aware), prefixed or not.
* you use a queryset with an unspecified language, which hvad understands as *"use whatever language is the default language at the time of the request"*.
* when you use a prefixed version, the language middleware from Django will set the appropriate language as default, so that gets the expected translation.
* when you use the un-prefixed version, Django's language middleware tries to do some magic to guess a language. Hvad will then proceed to use whatever was set, so check the documentation of Django's LanguageMiddleware to see whether its algorithm suits your needs.
* also, by default, if the browser sends a `language_code` field when POSTing, that will override the language setting for this request. That means that, by default, you can POST to the `it` uri and include a `language_code` field giving another language, the field will win over the `it` par in the uri.

All of those behaviors can be overriden. Depending on the specific behaviors you want, you will want to override either `get_queryset` and/or `get_serializer`. For instance you could disable `language_code` overriding and enforce that the correct language is always used. You would do it this way:
```python
from django.utils import translation

    # in your viewset class
    def get_serializer(self, *args, **kwargs):
        # set the serializer to language-enforcing mode
        kwargs['language'] = translation.get_current()
        return super(WebsiteViewSet, self).get_serializer(*args, **kwargs)
```
That would make sense for your prefixed uris. Note that the browser should not send a `language_code` anymore in that case, or a `ValidationError` will be raised.

By the way, about the `language_code` not being output: if you want the `language_code` field to be output in the serialized form, you must include it in the `fields` list.

Hope it helps, will look at 1) a bit later.

**Comment by paolostefan** [comment]
Hello, thanks a lot. Your last post definitely clarified the logic behind and I think this bit should become part of the official documentation, as well as the working example you set up for me. 
Just a side note: my `Website` model had a translated field named `url`, which is the field name used by the `HyperlinkedTranslatableModelSerializer` for linking the records. If you plan to use it in the docs, this field name should change to a non-reserved field, e.g. `translated_url`.

**Comment by spectras** [comment]
Yeah, you're right. The basic rules are in the documentation, but figuring out how they interact with Django's LanguageMiddleware can be tricky, I'll add it to the documentation for next release.

Did you manage to make `TranslationsMixin` work?
There are two ways to use it. Either standalone or mixed:
```python
class MySerializer(TranslationsMixin, ModelSerializer):
    # etc.
```
Note how it is associated with a regular `ModelSerializer` and not a translatable one. In this case, translations will be output as a dictionary. That could make sense for your non-prefixed URI for instance.

You can also mix this with a `TranslatableModelSerializer` instead. If you do so:

* the translations dict will be output.
* one of the translations will be duplicated onto the model.
* the duplicated fields will be read-only.

For instance, this could be a possible serializer:
```python
class SampleSerializer(TranslationsMixin, TranslatableModelSerializer):
    class Meta:
        model = Website
        fields = ('name', 'description', 'url', 'language_code')
```
That would produce the following JSON object:
```json
{
    "name": "example",
    "description": "a description in English",
    "url": "http://description.uk/",
    "language_code": "en",
    "translations": {
        "en": {
            "description": "a description in English",
            "url": "http://description.uk/"
        },
        "fr": {
            "description": "une description en français",
            "url": "http://description.fr/"
        }
    }
}
```
The `description`, `url` and `language_code` field on the root object are read-only copies of the English translation, to change them you must use the original, in the `translations` sub-dict.

**Comment by paolostefan** [comment]
Yes, I managed to get TranslationsMixin to work, thanks.
Now I'm stuck with another error :(
Even the simple procedure described (here)[http://django-hvad.readthedocs.org/en/latest/public/quickstart.html#create-a-translated-instance] is failing with this error:
```
NoTranslationError at /api/v1/bookmark/
Accessing a translated field requires that the instance has a translation loaded, or a valid translation in current language (it) loadable from the database
```
Maybe I'm too much of a newbie in Django, but I cannot figure out what I'm missing.
Please note: the error pops up when I try:
```python
website = Website.objects.language('en').create(
    # untranslated fields
)
```
and the same with:
```python
# No language code
website = Website.objects.language().create(
    # untranslated fields
)
# No language at all
website = Website.objects.language().create(
    # untranslated fields
)
# Nothing at all
website = Website()
```
Any help is appreciated.

**Comment by paolostefan** [comment]
I'm closing this issue, I guess my last post deserves a better error description.

**Comment by spectras** [comment]
Just to be sure: was this last post the subject of your #240 ?

**Comment by paolostefan** [comment]
@spectras yes it was indeed. Thank you.
