### ISSUE TITLE
Exception for NoTranslationError

### ISSUE THREAD

**Issue by psychok7** [KristianOellegaard/django-hvad#239]
Hey there, so i am getting a `NoTranslationError` in my self.address field on my model and i am trying to catch that exception to avoid crashing the site.   

```
  __original_address = None

    def __init__(self, *args, **kwargs):
        super(BlaBla, self).__init__(*args, **kwargs)
        self.__original_address = self.address
```

I am doing this so i can compare de original address with the new one and only if they are different i do something.

HOw can i do an exception to ignore this NoTranslationError here??
cheers

**Comment by spectras** [comment]
Hello!
Well, the `NoTranslationError` is a subtype of `AttributeError`. That means the following will work:
```python
    # Simply using getattr with a default
    self.__original_address = getattr(self, 'address', None)

    # Using hasattr
    if hasattr(self, 'address'):
        # do something here

    # Catching the exception itself
    try:
        self.__original_address = self.address
    except AttributeError:
        # handle error here, or just pass to ignore
```
You might also want to try out this one:
```python
    self.__original_address = self.safe_translation_getter('address', None)
```
This one is guaranteed to never perform a query to the database, simply using currently loaded translation, if any, but never attempting to check the database. If you're simply caching stuff, it might be a better option than `getattr`.

By the way, completely unrelated to hvad and your question, I think there are some gotchas to be aware of when caching attributes the way you are doing it. Namely, if you run a multi-process or multi-thread server, your cache might be out of sync at the time you actually save your instance.
Just a thing to be aware of :)

**Comment by psychok7** [comment]
thanks @spectras it worked like a charm ;)

**Comment by spectras** [comment]
You're welcome!
