### ISSUE TITLE
NoTranslationError when a translated field has the same name of an untranslated field

### ISSUE THREAD

**Issue by paolostefan** [KristianOellegaard/django-hvad#240]
I ran into this issue and it took me quite a while to figure it out (maybe it's silly to name translated and untranslated fields the same, but I was allowed to do it ;-).

This model works just fine:

```python

class Website(TranslatableModel):
	
	default_url = models.URLField(max_length=100,unique=True)

	edited 		= models.DateTimeField(auto_now=True)
	edited_by 	= models.ForeignKey(User, related_name='+', blank=True, null=True)

	translations = TranslatedFields(
		tr_url = models.URLField(max_length=100, null=True, blank=True),
		tr_description = models.TextField(null=True,blank=True),
		tr_edited  = models.DateTimeField(auto_now=True),
		tr_edited_by = models.ForeignKey(User, blank=True, null=True),
	)

```

whereas this one fails even to instance (please note the `edited` and `edited_by` translated fields):

```python

class Website(TranslatableModel):
	
	default_url = models.URLField(max_length=100,unique=True)

	edited 		= models.DateTimeField(auto_now=True)
	edited_by 	= models.ForeignKey(User, related_name='+', blank=True, null=True)

	translations = TranslatedFields(
		tr_url = models.URLField(max_length=100, null=True, blank=True),
		tr_description = models.TextField(null=True,blank=True),
		edited  = models.DateTimeField(auto_now=True),
		edited_by = models.ForeignKey(User, blank=True, null=True),
	)
```

The error message is not so self-explanatory:
> NoTranslationError: Accessing a translated field requires that the instance has a translation loaded, or a valid translation in current language (None) loadable from the database

Nevertheless, a model is allowed to have fields by the same name both globally and under `translations`, and migrating a model like the second one does not give any warning/error message.

Maybe this kind of model inconsistency should be explained by a more meaningful error message, or disallowed completely.

**Comment by spectras** [comment]
Hello,
Well, yeah it would definitely make sense to add a couple of checks for this kind of things. Maybe by leveraging the system check API that was introduced in Django 1.6.
Thanks for reporting that, it's likely I will do something about it before next release.

**Comment by spectras** [comment]
Proper checks are now on `master`. They will only run with Django 1.7 or newer (they use the new validation framework). Will be part of upcoming release 1.3.
Thanks again for the report.

**Comment by paolostefan** [comment]
Thanks a lot!

**Comment by kairatomurbek2** [comment]
I have there is an error while loading fikstures.json
hvad.descriptors.NoTranslationError: Problem installing fixture '/home/kayrat/projects/wng-src/web-application/fixtures.json': Accessing a translated field requires that the instance has a translation loaded, or a valid translation in current language (None) loadable from the database
