### ISSUE TITLE
UnicodeDecodeError in admin.py: render_change_form

### ISSUE THREAD

**Issue by callmewind** [KristianOellegaard/django-hvad#242]
Hi there,
I'm expecting this error when I try to edit a translatable model. Django admin is in spanish and the language to edit is 'Inglés - English', so it crashes trying to add Inglés in the page title. (Editing the 'Castellano - Spanish' tab works flaweless.
This is in django 1.7

**Comment by callmewind** [comment]
Nevermind, it was our own fault, I thought the string was coming from django's own language list but it was defined in our settings (and not in unicode). Sorry!

**Comment by spectras** [comment]
No worries, nice to hear you could fix your problem :)
