### ISSUE TITLE
`filter_horizontal` in the TranslatableAdmin

### ISSUE THREAD

**Issue by barseghyanartur** [KristianOellegaard/django-hvad#245]
I have a model with a ManyToMany field. In the admin (`TranslatableAdmin`) `filter_horizontal` does nothing. I see that `get_form` method of the `TranslatableAdmin` is tweaked. Any clear suggestions of how to enable the `filter_horizontal` are welcome.

**Comment by spectras** [comment]
I believe it should work as long as it only includes non-translatable fields (the admin's init procedure will complain it is misconfigured if it sees translatable fields, which it does not recognize, that's a recurring issue with internal admin checks that's tracked in #187).

Other than this, this part is mostly untouched. We inherit django's admin so we can inject the language links, but that's about it.
When you say it does nothing, do you mean it appears but doesn't work, or it does not even appear at all?

**Comment by spectras** [comment]
Here is where I am:
I built a sample app, with Book and Library model, and a M2M field from Library to Books.

```python
from django.db import models
from hvad.models import TranslatableModel, TranslatedFields

class Book(TranslatableModel):
    translations = TranslatedFields(
        title = models.CharField(max_length=250),
        summary = models.TextField(blank=True)
    )

    def __str__(self):
        return self.title


class Library(TranslatableModel):
    name = models.CharField(max_length=250)
    books = models.ManyToManyField(Book, related_name='libraries', blank=True)

    translations = TranslatedFields(
        description = models.CharField(max_length=250, blank=True),
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'libraries'
```

```python
# app/admin.py
from django.contrib import admin
from hvad.admin import TranslatableAdmin
from app.models import Book, Library

class BookAdmin(TranslatableAdmin):
    pass

class LibraryAdmin(TranslatableAdmin):
    filter_horizontal = ['books']

admin.site.register(Book, BookAdmin)
admin.site.register(Library, LibraryAdmin)
```
That gives me a filter box at the top of the `books` field in Library editing form.
![filter_horizontal](https://cloud.githubusercontent.com/assets/5879675/7960211/100863f8-09ff-11e5-829a-c9847531b169.png)

I hope it helps. If not, could you please provide some sample code?

**Comment by barseghyanartur** [comment]
@spectras:

It was exactly as you described. The devil lies in the details. Instead of registering the subclassed `TranslatableAdmin` the original `TranslatableAdmin` was used.

Thank you for your efforts!
