### ISSUE TITLE
problem with Meta.ordering

### ISSUE THREAD

**Issue by birdsarah** [KristianOellegaard/django-hvad#252]
Hi,

I see that you implemented supporting the ordering field on Meta in 0.5.0 http://django-hvad.readthedocs.org/en/latest/public/release_notes.html?highlight=ordering#id8

When I try and use it, I get the following error:
````bash
SystemCheckError: System check identified some issues:

ERRORS:
events.EventType: (models.E015) 'ordering' refers to the non-existent field 'description'.
````

Here is my model code:

````python
class EventType(TranslatableModel):
    translations = TranslatedFields(
        description=models.CharField(max_length=100),
        about=models.TextField()
    )

    class Meta:
        verbose_name = 'Type'
        verbose_name_plural = 'Types'
        ordering = ['description']
````

Can you spot what I've done wrong, or has something changed in Django - I'm on Django 1.8.2.

**Comment by spectras** [comment]
Hmm, Django did not perform any check at that time. I guess they added it recently.
...
Alright, found it. It was added in version 1.7. Our tests did not trigger them because we test that the feature works, not that it passes Django's validation.

I have to add that I guess.

**Comment by birdsarah** [comment]
Thanks for the quick reply @spectras - much appreciated - and hvad much appreciated!

**Comment by spectras** [comment]
You're welcome!
By the way, fix is now available on `master`, and will be including in upcoming release 1.3.
Thanks for reporting the issue.

By the way, remember that when using `Meta.ordering`, every query will be sorted, which could have a significant performance impact. Hvad supports is because Django does, but I would recommend explicitly ordering the requests you need ordered instead.

**Comment by birdsarah** [comment]
Thanks so much - that's fantastic!

**Comment by fidelmak** [comment]
I had the same issue recently and I was able to rectify it, using 

class Meta:
        ordering = [-1]
