### ISSUE TITLE
TranslationManager: values() fails with cryptic error message for language('all')

### ISSUE THREAD

**Issue by leifurhauks** [KristianOellegaard/django-hvad#264]
if `BulletinBoard` is a translated model, a cryptic `TypeError: 'NoneType' object does not support item assignment` is raised when `BulletinBoard.objects.language('all').values()` is called. Same thing for `values_list`.

Is this operation supported? If not, it would be helpful to explicitly raise an exception with a clear message.

**Comment by spectras** [comment]
Hello,
What Django version are you running? I believe the inner workings of `values()` and `values_list()` changed in the latest version, so it might be the reason.

**Comment by leifurhauks** [comment]
I'm running Django 1.8 with Python 3.4 and the latest django-hvad.

**Comment by spectras** [comment]
That might be it then, `values()` used to build a special queryset class which hvad had to override, but since version 1.8 they dropped the special queryset class, and hvad might still be trying to override it. I will check this tomorrow.

**Comment by spectras** [comment]
Sorry, I was a bit busier than I expected.
Fixed on master. The fix will be included in next release.
