### ISSUE TITLE
MySQL error while trying to save TranslatableModel with ManyToMany field related to other TranslatableModel

### ISSUE THREAD

**Issue by sphericalhorse** [KristianOellegaard/django-hvad#267]
I have 2 models with custom managers as default:

    class FallbackManager(hvad_manager.TranslationManager):
        def get_queryset(self):
            return super(FallbackManager, self).language().fallbacks()
    class Contacts(TranslatableModel):
        fallback = FallbackManager()
        translations = TranslatedFields(
            name = models.CharField(),
        )
        ...
    class Event(TranslatableModel):
        fallback = FallbackManager()
        translations = TranslatedFields(
            title = models.CharField(),
        )
        contacts = models.ManyToManyField(Contacts)
        ...

So when I try to save Event object using Django admin, I get an error:

    (1093, "You can't specify target table 'app_event_contacts' for update in FROM clause")

SQL-query that caused error:

    DELETE FROM `app_event_contacts` WHERE (`app_event_contacts`.`event_id` = 16 AND (`app_event_contacts`.`contacts_id`) IN (SELECT U0.`id` FROM `app_contacts` U0 INNER JOIN `app_event_contacts` U1 ON ( U0.`id` = U1.`contacts_id` ) WHERE U1.`event_id` = 16))

Error appeared when I added the field `contacts` to Event model.
Also I dont get this error when dont use custom manager for Contacts model.

**Comment by spectras** [comment]
Hello,

So, a quick guess is the admin sets the list of contacts using assignation. Doing so would trigger `manager.clear()` on the related manager. If I remember well, Django builds the related manager from the first manager it encounters when reading the model definition. So here, it tries to use `clear` on `FallbackManager`.

That edge case is not tested. You should be able to fix it by making sure the default manager is a regular `TranslationManager`, by specifying it first:

```python
class Event(TranslatableModel):
    objects = TranslationManager()
    fallback = FallbackManager()
```

**Comment by spectras** [comment]
Without hearing back, I'll assume your issue is fixed. Please feel free to reopen as needed.
