### ISSUE TITLE
Want to translate Django User model first_name and last_name

### ISSUE THREAD

**Issue by ahmedsalman** [KristianOellegaard/django-hvad#269]
Hi 
I  want to translate my from **django.contrib.auth.models import User** Model's *first_name* and *last_name*. I am aware of Custom User Model in Django. But is there any better way of translating using django Hvad

For reference i am attaching my Model here

 class UserProfile(TranslatableModel):

     translations = CustomTranslatedFields(

         bio=models.TextField(
             verbose_name=_('Biography'),
             blank=True
         ),

     )

     user = models.OneToOneField(
         User,
         related_name='user_profile',
         verbose_name=_('User Profile'),
     )

     default_language = models.CharField(
         max_length=2,
         choices=LANGUAGES,
         default='en'
     )

As you can see bio field is translatable but how would i be able to translate my User models first_name and last_name field

**Comment by spectras** [comment]
There are two paths you can follow: 

1. is to substitute Django's user model for your own. I found it to not be too reliable unfortunately, as some third party packages depend on it.
2. is to simply ignore the fields you don't need. For your example, I would just put `first_name` and `last_name` fields into `UserProfile` and not use those from Django's model at all (that is, leave them blank).

As a side-note, you might want to switch from first+last fields to something else. Depending on cultures, names are not split that way. I would just have `full_name`. And if you really want to, add a `short_name` on top of that. That way, your UI can split the name appropriately depending on the language.

**Comment by ahmedsalman** [comment]
Thank you for quick reply and very nice suggestion. it worked for me :-) cheers  Thanks
