### ISSUE TITLE
Unique values' behavior

### ISSUE THREAD

**Issue by alexshin** [KristianOellegaard/django-hvad#270]
When I created a new unique field in TranslatableModel django-hvad had prohibited me to create some records on different languages with the same value. There are some languages with similar words e.g. russian, belarusian and ukranian.

I think a right behavior will be to check unique values only in one language.

What do you think about it?

**Comment by spectras** [comment]
Hello,
Both actually work. By default, it will check in all languages, but you can make it be by language only like this:

```python
class MyModel(TranslatableModel):
    translations = TranslatedFields(
        some_field=models.CharField(max_length=255),
    )
    class Meta:
        unique_together = [('language_code', 'some_field')]
```
Like this, the field `some_field` will be unique, by language.

**Comment by spectras** [comment]
I'll consider this ticket solved. Please feel free to open it again, or open another ticket should you need it.
