### ISSUE TITLE
Mysql multicolumn indexes only match starting with leftmost fields

### ISSUE THREAD

**Issue by Morpho** [KristianOellegaard/django-hvad#271]
Multicolumn indexes in mysql only match the leftmost field. Before there was no index being used for "master_id". See http://dev.mysql.com/doc/refman/5.7/en/mysql-indexes.html

https://github.com/Morpho/django-hvad/commit/ee86480d351791b1bb32eb4d845a1307faf7cdf3

**Comment by Morpho** [comment]
The final result of our table optimizations was actually this:

UNIQUE KEY `uniindexkey` (`master_id`,`language_code`),
KEY `indexkey` (`language_code`,`master_id`)

So, in Django terms:

index_together = (('language_code', 'master'), )
unique_together = (('master', language_code'), )

**Comment by spectras** [comment]
Hello,

That's interesting. Hvad only specifies the `unique_together` part and lets Django work on other relevant indexes. In particular,
 * Django should create a regular index for `master_id` automatically.
 * Hvad tells Django it wants an index of `language_code`.
 * Hvad tells Django it wants a unique_index on `[language_code, master_id]`.

On PostgreSQL, Django ends up creating exactly what's requested (two one-column indexes and the unique_index on both together, all three b-tree). Which is a bit overkill as postgresql can re-use multi-column indexes for single-column queries.

I wonder how the result you describe happens. Is it a new behavior that showed up as part of upgrading either hvad or Django? Does it do that when creating the table, or does it appear after running a migration? Which version of Django are you using?

**Comment by Morpho** [comment]
Hi spectras,
thanks for the quick response. We just recently switched from "django-modeltranslations" to hvad. So we basically installed the latest hvad version from pypi and ran the migrations for our models after adding translation fields etc as described in the tutorial.

Django==1.7.7
django-hvad==1.4.0

Regular indexes for master_id and language_code were not present in our mysql tables. We added a new multi column index with "master" being on the most left hand side and afterwars everything went smooth.

**Comment by spectras** [comment]
I am in the process of trying to reproduce the issue. I build a small app with a simple model:

```python
class Book(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=250)
    )
```
Using Python3.4, Django 1.7.7, hvad 1.4.0 and mysqlclient adapter 1.3.7 gives me this migration file:

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models, migrations

class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BookTranslation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('language_code', models.CharField(max_length=15, db_index=True)),
                ('master', models.ForeignKey(editable=False, related_name='translations', null=True, to='app.Book')),
            ],
            options={
                'db_table': 'app_book_translation',
                'default_permissions': (),
                'managed': True,
                'db_tablespace': '',
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name='booktranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]

```
Which, once applied, results in the following in mysql (v5.6.27):
```sql
CREATE TABLE `app_book_translation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(250) NOT NULL,
  `language_code` varchar(15) NOT NULL,
  `master_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `app_book_translation_language_code_1ef776dbdb7dadde_uniq` (`language_code`,`master_id`),
  KEY `app_book_translation_60716c2f` (`language_code`),
  KEY `app_book_translation_90349b61` (`master_id`),
  CONSTRAINT `app_book_translation_master_id_7bcec9fbfcddc271_fk_app_book_id` FOREIGN KEY (`master_id`) REFERENCES `app_book` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

So everything looks perfectly normal, though I would have expected the `language_code` index not to be created since mysql can use the unique one in that case.

But that's starting from scratch, so if the issue came from how Django diffs the database, it won't show. I should try again, building a non-translatable book model first, migrating it next to see how Django reacts. Hmmmm…

**Comment by spectras** [comment]
Nope, I also tried creating a vanilla Book model, migrating it, and adding translations after, and everything is working fine. I also checked, in no circumstances may `hvad` create an `index_together` by itself.

Is the issue reproductible on your side?

Also, I see this warning in Django documentation: 
*MySQL lacks support for transactions around schema alteration operations, meaning that if a migration fails to apply you will have to manually unpick the changes in order to try again (it’s impossible to roll back to an earlier point).*

So in the event you might have tried to apply a migration that failed, it might have confused Django enough that it mixed up the next attempt as well.

**Comment by Morpho** [comment]
Hi, I'm really sorry for all the work I caused you. I analyzed it further and it seems that in fact django or mysql just don't create these indexes without complaining when the creation of a foreign key constraint fails. I checked with django-extension's sqldiff command and there it's clearly visible that django was supposed to create these indexes, but they werent created:
```
-- Model: MyModelResultTranslation
CREATE INDEX `nametest_MyModelresult_translation_language_code`
        ON `nametest_MyModelresult_translation` (`language_code`);
CREATE INDEX `nametest_MyModelresult_translation_language_code_like`
        ON `nametest_MyModelresult_translation` (`language_code` varchar_pattern_ops);
CREATE INDEX `nametest_MyModelresult_translation_master_id`
        ON `nametest_MyModelresult_translation` (`master_id`);
```

So from hvad's side everything is fine. Thanks again for your quick help!

**Comment by spectras** [comment]
No worries, I'm glad you could identify the cause.
Feel free to open another issue should you need it.
