### ISSUE TITLE
Can't call MyModel.objects.all() to return all objects without translated fields

### ISSUE THREAD

**Issue by KhumpuW** [KristianOellegaard/django-hvad#276]
I'm using version 1.4.0
although MyModel.objects.language('..') works fine.
I want to be able to call MyModel.objects.all() because 3rd party plugin called Django-Admin-Sortable.  It need to access untranslated fields by calling .objects.filter(..) to work correctly.

**Comment by spectras** [comment]
Hello,
I am not familiar with that module, could you elaborate on what you're trying to do, and what error or unexpected behavior you see?

**Comment by KhumpuW** [comment]
there is a function in the Django-Admin-Sortable plugin that's executed when user drag and drop item to sort model in Admin Interface.

MyModel class is inherited from TranslatableModel and has a SortableMixin from Django-Admin-Sortable plugin which is look like this.

class MyModel(SortableMixin, TranslatableModel):
    translations = TranslatedFields(...)
    order = models.PositiveIntegerField(default=0, editable=False, db_index=True) # for django-admin-sortable
    class Meta:
        ordering = ['order']

I try debug in Django-Admin-Sortable sort function and find out this line cause a problem:

* klass is a MyModel class. *
objects_dict = dict([(str(obj.pk), obj) for obj in
                    klass.objects.filter(pk__in=indexes)])

the problem is klass.objects.filter() fail to retrieve some of MyModel instances in indexes

The problem won't occurs if all MyModel instances in indexes are fully translated.
EX: let's say I have 2 languages in my project and 3 MyModel instances in my database 
instance 1: EN, TH
instance 2: EN, TH
instance 3: EN, TH

The problem occurs if there is at least 1 instance of MyModel in indexes and this code klass.objects.filter() fail cause error when it try to get that instance.
EX: same as above but now with some of instance that is not fully translated
instance 1: EN, TH
instance 2: EN <--- fail to get this instance
instance 3: EN, TH

and here's the weird thing let's say I have these instance
EX:
instance 1: EN, TH
instance 2: EN
instance 3: EN, TH

If I go to admin interface in EN language I can sort them perfectly fine.
If I go to admin interface in TH language I can't sort them. because this line klass.objects.filter() can't get instance 2

I read the Hvad readme in Github, it says that  this code Book.objects.all().  returns all objects, without any translated fields attached.
but in my case why doesn't this line of code klass.objects.filter() work?
If I understand correctly, shouldn't it work perfectly with klass.objects.filter() because all it's trying to is to work with untranslated field even without fully translated instance?
Shouldn't it return all instances of MyModel without untranslated field?

* If there's no way to make klass.objects.filter() work with not fully translated model.
Is there a way to let other language of an instance created as the same data when user create just 1 language?

Thank you.

**Comment by spectras** [comment]
I am trying to understand how that package, django-admin-sortable, works. If I understand what you said, everything seems to be working fine, except you cannot actually sort the items? Because that function you pointed, which is called with AJAX, cannot find one of the objects?

You are right, the `filter()` method should retrieve all objects, with no translations attached. But this behavior can be customized to automatically filter by language. Do you have a custom manager / custom queryset defined for this model? Could you post your `objects = ` declaration of your model if you have one?

As an alternative, it would be possible to overload the `do_sorting_view` method from `SortableAdmin` to explicitly use `klass.objects.untranslated().filter(…)`.

**Comment by KhumpuW** [comment]
No, MyModel don't have any custom objects defined, and I wonder why doesn't filter works?

class AppContent(SortableMixin, TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(max_length=255, default=''),
        feed_title=models.CharField(max_length=255, default=None, null=True, blank=True),
        description=models.CharField(max_length=255, default=None, null=True, blank=True),
        image=FilerImageField(default=None, null=True, blank=True),
        start=models.DateField(default=None, null=True, blank=True),
        end=models.DateField(default=None, null=True, blank=True),
        created=models.DateTimeField(default=timezone.now, editable=False),
        modified=models.DateTimeField(default=timezone.now, editable=False),
    )

    content_placeholder = PlaceholderField('content')
    order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    class Meta:
        abstract = True
        ordering = ['order']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(AppContent, self).save(*args, **kwargs)

**Comment by spectras** [comment]
In the shell, it is normal: your `__str__` method uses a translatable field, so when the shell tries to display an object, calling `__str__`, you get that error. You should change your method to this:

```python
def __str__(self):
    return self.safe_translation_getter('title', str(self.pk))
```
This way, if no translation is loaded, the shell will display the id instead of just raising an error.

**Comment by spectras** [comment]
Actually your `save` method has the exact same issue: it tries to access `self.created` and `self.modified`. When loading the object without translations loaded, that will attempt to load one, and raise an error if that fails.

I assume those field are actually related to each translation, not to the object itself (that is, each translation has its own `modified` field that should only change when that specific translation is updated). If so, then `save` should just skip updating those field if you are not going to update a translation.

You can use `hvad.utils.get_cached_translation` to know whether a translation is loaded or not, like this:
```python
    from hvad.utils import get_cached_translation
    def save(self, *args, **kwargs):
        if get_cached_translation(self) is not None:
            if not self.id:
                self.created = timezone.now()
            self.modified = timezone.now()
        return super(MyModel, self).save(*args, **kwargs)
```
Normally, you should have a list of fields to set passed to `save` and could use this instead, but I see that django-admin-sortable does not follow this convention.

**Comment by KhumpuW** [comment]
The problem is in my model function all along. I've been so blinded. Thank you so much.

**Comment by spectras** [comment]
You're welcome, feel free to open other issues here if you need :)
