### ISSUE TITLE
Serializing ForeignKey to untranslated model fails with WrongManager exception

### ISSUE THREAD

**Issue by dgaus** [KristianOellegaard/django-hvad#278]
Hi, I have the following models

```
class Node(models.Model):
    pass

class Document(TranslatableModel):
    translations = (
        title = models.TextField()
        root_node = models.ForeignKey('Node')
    )
```

Now, I defined my DRF serializers like so

```
class DocumentSerializer(TranslationsMixin, ModelSerializer):
    class Meta:
        model = Document
        fields = ['id', 'translations']
```

The problem is, doing

```
t = Document.objects.get()
s = DocumentSerializer(t)
s.data
```
raises a `WrongManager` exception. I have tried redefining the serializer as

```
class DocumentTranslationSerializer(ModelSerializer):
    root_node = PrimaryKeyRelatedField(queryset=get_translation_aware_manager(Node))
    title = CharField()

class DocumentSerializer(TranslationsMixin, ModelSerializer):
    class Meta:
        model = Document
        fields = ['id', 'translations']
        translations_serializer = DocumentTranslationSerializer
```

But it seems to have no effect. Adding `exclude = ['root_node']` to the translations serializer displays only the title and it works as expected. Am I missing something? Thanks

**Comment by spectras** [comment]
Hello,

Thanks for reporting. It seems you found a bug in hvad's rest_framework support.
I investigated and was able to find the root issue, namely rest_framework handles related fields in a special way that goes around hvad, making it fail to access translated foreign keys. I was able to build a failing example based on your input, I have to make it a proper test case, and work from there.

Good news is your original code (model and serializer) should work once the bug is fixed. I will try to block some time to work on it tomorrow.

**Comment by dgaus** [comment]
Thanks a lot for the prompt reply. After posting this I found a workaround, which is making `root_node = IntegerField(source='root_node_id')` in the translation serializer. This skips the serializer validations, so incorrect primary keys result in server errors, therefore it's not ideal, but our API is not public so it works for now. Looking forwards to a proper fix :) cheers

**Comment by spectras** [comment]
Sorry for not coming back sooner, I spent the last 2 days in bed with fever. I'm slowly getting better, I'll fix it when I am well enough I'm sure I won't introduce bugs in the process.

**Comment by dgaus** [comment]
No worries! get well soon

**Comment by spectras** [comment]
Thanks, I'm much better, still a bit tired.
I pushed a fix to master, it will be included in next release.

**Comment by spectras** [comment]
Release 1.5.0 is out, which should fix this issue.
Thanks again for taking the time to report here.

**Comment by dgaus** [comment]
That's great, thank you!
