### ISSUE TITLE
Page not found error in Admin detail when using abtract meta model

### ISSUE THREAD

**Issue by webjunkie** [KristianOellegaard/django-hvad#280]
I previously had good results with using django-hvad for projects, but installing it with Django 1.9.1 I always get a 404 page not found on the object detail page when using the ``TranslatableAdmin``.
I'm using a meta model with a ``UUIDField``. The error is not happening with a normal model. I'm still trying to figure out what goes wrong, but maybe someone knows more?

**Comment by webjunkie** [comment]
To reproduce:

    class BaseModel(models.Model):
        id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
        created = models.DateTimeField(auto_now_add=True)

        class Meta:
            abstract = True

    class Solution(BaseModel, TranslatableModel):
        translations = TranslatedFields(
            name=models.CharField(max_length=255),
            description=models.TextField(),
        )

**Comment by webjunkie** [comment]
Seems this is just in 1.4.0 but doesn't affect the current master.

**Comment by spectras** [comment]
Alright, I'm glad, though I'll try to reproduce it on 1.4.0 and add a test case to make sure it does not come back at a later point.
Thanks for reporting :)
