### ISSUE TITLE
get_object_or_404 and other Django shortcuts

### ISSUE THREAD

**Issue by elenaoat** [KristianOellegaard/django-hvad#281]
I guess there's no implementation for get_object_or_404 in hvad. I was wondering if it would be sensible to have one?

**Comment by spectras** [comment]
I feel it would be a bit overkill, as one can use Django's implementation easily. It accepts querysets as well as models, so it is possible to do this:
```python
obj1 = get_object_or_404(MyModel.objects.language('en'), pk=42)
obj2 = get_object_or_404(MyModel.objects.untranslated(), pk=42)
```
