### ISSUE TITLE
show language_code on admin

### ISSUE THREAD

**Issue by gitpronik** [KristianOellegaard/django-hvad#282]
hi how can i list language_code on admin panel.
list_display = ('title', 'language_code') not working !

**Comment by spectras** [comment]
Hello,

I assume you're getting an error from Django checks, telling you that  `language_code` is an invalid field name, right?
If so, it is a common issue that third party modules such as hvad encounter when they add custom fields, it can be worked around by using the `get_list_display` method instead:

```python
    def get_list_display(self, request):
        return ('title', 'language_code')
```
