### ISSUE TITLE
Error in admin using Django 1.9

### ISSUE THREAD

**Issue by Tyrdall** [KristianOellegaard/django-hvad#283]
Hi,

I'm using your ``TranslatableAdmin`` in Django 1.9.3. The following error appears when calling the admin pages: 

    To use select_related on a translated model, you must provide a list of fields.

The relevant line can be found in Django's admin views:

https://github.com/django/django/blob/master/django/contrib/admin/views/main.py#L364

If I remove the only foreign key field from ``list_display`` it's working.

**Comment by spectras** [comment]
Hello,

To use `select_related` with hvad, a list of field must be explicitly provided, otherwise a flood of joins would ensue. I think Django's admin allows a [`list_select_related`](https://docs.djangoproject.com/es/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_select_related) setting to provide an explicit set of `select_related` fields. Could you try with that?

**Comment by Tyrdall** [comment]
@spectras Thanks for your fast response and the advice. Now the following error is thrown:

    Using select_related along with fallbacks() is not supported

**Comment by spectras** [comment]
Hmm that's true, I had forgotten it uses fallbacks. This means it cannot use `select_related` indeed.

I am looking at Django's admin code. It seems there is no way to prevent it from calling `select_related`. Oddly, it can be forced to do always do it, but there is no option to force it to never do it.

I suggest you override the whole function like this:

```python
    def apply_select_related(self, qs):
        return qs.prefetch_related('some_relation', 'some_other_relation')
```

Hopefully that should be enough, if it does not hit the `WrongManager` case. The admin code being older than me joining the project, I don't know its inner details as well as the rest.

**Comment by Tyrdall** [comment]
@spectras I don't want to overwrite Django's admin views, so I just created a simple function to retrieve the foreign key object:

    def get_xxx(self, obj):
        return obj.xxx
    get_xxx.short_description = _('XXX')

Thanks a lot for your support!

**Comment by spectras** [comment]
It will work indeed. It does have the drawback of generating one additional query per object displayed in the admin. If at some point this becomes problematic, remember there is always the possibility of overriding the `apply_select_related` to prefetch all translations at once.

And should you have any issues doing that, simply re-open this :)

**Comment by callmewind** [comment]
Hi,
Just want to say that I just stepped into this bug. Overriding the  admin view seems much hassle (we're not talking about overriding a modeladmin function, that would be easier).

Spectras's solution works, but it's a workaround and at least should be documented somewhere. Also, this bug didn't exist in previous versions (django 1.8 or less).

**Comment by spectras** [comment]
Indeed, Django 1.9 introduced the “intelligent” automatic `select_related` which breaks. Unfortunately it did not care to make it easily overridable. I guess I could try to see if it can be circumvented at the *hvad* level. Alas, with every new Django version, the admin part seems to be more and more closed to third-party modules such as *hvad*. What should be simple feature augmentations is slowly getting forced into being more and more of a kludge.

I'm adding the v2 milestone, as this is definitely something that needs a better solution at some point.

**Comment by patroqueeet** [comment]
call me stupid, but does not seem to work for me. my code:

```
23 class CompanyDescriptionAdmin(TranslatableAdmin):
   24     model = CompanyDescription
   25     readonly_fields = ('updated_at', 'created_at')
   26     list_filter = ('company', )
   27     list_display = (description_text, 'company',)
   28     formfield_overrides = {
   29         models.TextField: {'widget': forms.Textarea(
   30             attrs={'rows': 8, 'cols': 80}), },
   31     }
   32     list_select_related = ('company',)  # see hvad#283
   33
   34     # see hvad#283
   35     def apply_select_related(self, qs):
   36         return qs.prefetch_related('company')
```

gives me: `Using select_related along with fallbacks() is not supported`

**Comment by patroqueeet** [comment]
found a working solution:

```
   23 class CompanyDescriptionAdmin(TranslatableAdmin):
   24     model = CompanyDescription
   25     readonly_fields = ('updated_at', 'created_at')
   26     list_filter = ('company', )
   27     list_display = (description_text, 'get_company',)
   28     formfield_overrides = {
   29         models.TextField: {'widget': forms.Textarea(
   30             attrs={'rows': 8, 'cols': 80}), },
   31     }
   32
   33     # see hvad#283
   34     def apply_select_related(self, qs):
   35         return qs.prefetch_related('company')
   36
   37     def get_company(self, obj):
   38         return obj.company
```

**Comment by spectras** [comment]
@patroqueeet > indeed, if you choose the path of applying it yourself, you should not tell django's admin to do it (which is the root cause of the issue anyway). Glad you could fix it right away.

**Comment by light1988** [comment]
@spectras @Tyrdall @patroqueeet I do not know what i am doing wrong but none of your solutions works for me. I am using django 2.2.

Here is my admin class:

```
class TownAdmin(RichTextAreaMixin, ImageCroppingMixin, ImportExportModelAdmin, TranslatableAdmin):
    exclude = ()
    readonly_fields = ()

    list_display = ['id', 'name', 'get_province', 'zip_code', 'active', 'main_city']
    search_fields = ['name','zip_code', ]
    list_filter = ( 'active','main_city', 'province',   )
    ordering = ['name']

    def apply_select_related(self, qs):
        return qs.prefetch_related('province')

    def get_province(self, obj):
        return obj.province

admin.site.register( Town, TownAdmin )
```

If i use @patroqueeet solution i don't get errors anymore but my admin list appears empty like there are no elements...
