### ISSUE TITLE
No default language

### ISSUE THREAD

**Issue by eugened19** [KristianOellegaard/django-hvad#289]
Hi guys,

Where do you stand on this issue?

http://stackoverflow.com/questions/17001383/translate-django-model-fields-without-having-a-default-language

Is this case (having no default language) possible using django-hvad?

Thank you!

**Comment by spectras** [comment]
Hello,

*hvad* does not have the concept of a default language. You can either:

 - use untranslated versions of your models, using `.untranslated()`.
 - or specify a language to load, using `.language('en')`.

In the latter case, you may omit the language (`.language()`), which *hvad* interprets as *“ask Django what the currently active language is and use that”*. If your Django is configured correctly, that language should be that of the request being handled.

Under the hood, *hvad* is very different from the package you linked. *hvad* uses a separate table for translated fields.

Hope it helps, feel free to ask if you need more details.

**Comment by eugened19** [comment]
Got it. Seems what I need.
Thank you! 

I'll give hvad a try.
