### ISSUE TITLE
set translated field in admin's save_model?

### ISSUE THREAD

**Issue by bevedoni** [KristianOellegaard/django-hvad#290]
I have a model: 

    class MyModel(TranslatableModel):
        translations = TranslatedFields(
            title=models.CharField(max_length=100,),
        )

and in admin.py in save_model() method, I am trying to set this field: 

    if form.cleaned_data.get('title', ''):
        obj.title = form.cleaned_data.get('title')
    elif obj.title == 'old_title':
        obj.title = '---'

and the field is not set correctly, am I missing somethign? is there any save_translated_fields() method in admin?

**Comment by spectras** [comment]
Hello,
I am not sure to understand what you are trying to do. The `TranslatableAdmin` should handle the field by itself. Actually, it does not alter the saving behavior in any way.
What do you have around the code you posted? What result do you expect, and what do you get instead?

**Comment by spectras** [comment]
I assume you managed to solve your issue. If not, feel free to open it again :)
