### ISSUE TITLE
 The model does not have a model_attr 'language_code'

### ISSUE THREAD

**Issue by stphivos** [KristianOellegaard/django-hvad#293]
We are facing this problem with a translatable model that doesn't always have model attribute `language_code` after is fetched from the db.

The scenario is that we have setup celery_haystack to signal model changes to django_haystack to update a search index.

I looked at the source code of all 3 libraries to sort of understand what's happening and it seems that celery_haystack does a `get(pk=46914)` on the model manager. Some times language_code is indeed not available. It seems like a race condition, but I can't explain it since hvad's way of accessing cached_translations attributes is blocking?

I used a for loop to check if it exists up to 100 times, before accessing the attribute and it seems that it works most of the time now. But it's a non-deterministic solution I would like to avoid:

```python
class MyTranslatableModel(TranslatableModel):
    class Manager(TranslationManager):
        def get(self, *args, **kwargs):
            print '### GETTING MODEL ###'
            obj = super(MyTranslatableModel.Manager, self).get(*args, **kwargs)
            for i in range(100):
                if not hasattr(obj, 'language_code'):
                    print '### Attempt {0}: No language code ###'.format(i + 1)
                else:
                    break
            return obj
```

It becomes available at random iteration `i`.

Also here is the traceback from celery_haystack:

```
[2016-05-18 17:54:46,268: ERROR/Worker-1] celery_haystack.tasks.CeleryHaystackSignalHandler[2f876d00-7546-4886-8c7c-6c172c4e3dd9]: The model '<MyTranslatableModel: 46914>' does not have a model_attr 'language_code'.
Traceback (most recent call last):
  File "/home/vagrant/our_python_env/local/lib/python2.7/site-packages/celery_haystack/tasks.py", line 124, in run
    current_index.update_object(instance, using=using)
  File "/home/vagrant/our_python_env/src/haystack/haystack/indexes.py", line 282, in update_object
    backend.update(self, [instance])
  File "/home/vagrant/our_python_env/src/haystack/haystack/backends/elasticsearch_backend.py", line 171, in update
    prepped_data = index.full_prepare(obj)
  File "/home/vagrant/our_python_env/src/haystack/haystack/indexes.py", line 212, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/vagrant/our_python_env/src/haystack/haystack/indexes.py", line 203, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/vagrant/our_python_env/src/haystack/haystack/fields.py", line 159, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/vagrant/our_python_env/src/haystack/haystack/fields.py", line 87, in prepare
    raise SearchFieldError("The model '%s' does not have a model_attr '%s'." % (repr(current_object), attr))
SearchFieldError: The model '<MyTranslatableModel: 46914>' does not have a model_attr 'language_code'.
```

Is there any way to make sure language_code is always present at the model manager when `get(pk=46914)` is run? I tried pre-fetching the translations but no luck.

Thank you.

**Comment by spectras** [comment]
Hello,

As it's running in Celery, I assume it is running in parallel to the code creating the object?
Hvad proceeds in the following way:

1) Save the master object
2) If some translated fields are to be saved, then save the translation object.

This is not run in a transaction by default, so user code can choose whether it wants one, or whether it wants handle the cases in which the translation has not been saved yet gracefully.

So it would look like the celery process is awaken and starts handling the new object before `hvad` has completed the save.

As a sidenote, depending on which fields are saved (using the `update_fields` argument of `save()`), `hvad` will intelligently save either `MyTranslatableModel`, `MyTranslatableModel._meta.translations_model` or both. So you might want to have both trigger your celery code.

In this case, creating a new object will trigger two events, one for “new object created” and one for “new translation created”.

Tell me if it helps. I'll do my best to answer quickly, but please now I am in remote areas atm, so internet access comes and goes.

**Comment by stphivos** [comment]
Hi @spectras and thanks for your help. You're right since `celery_haystack` runs asynchronously it often runs before hvad has completed the save.

I looked at the code you mentioned where hvad decides whether to save either the translatable model or the translation or both. It seems tracking the translatable model can be too early since that depends on the translation to be able to return a value for `language_code`. I will try triggering celery only after the translation is saved. Can't think off a better option but I don't see why this shouldn't work. I will let you know.

Cheers!

**Comment by spectras** [comment]
Since I didn't hear back, I'm assuming that it worked for you.
If it didn't, please feel free to re-open the issue.

Thanks a lot for taking the time to report here. :)

**Comment by stphivos** [comment]
We had to do a temp fix because a quick attempt didn't solve it. Let's keep it closed and when done properly I will report here, it should work. Thanks! :)
