### ISSUE TITLE
Compatibility with upcoming Django 1.10

### ISSUE THREAD

**Issue by spectras** [KristianOellegaard/django-hvad#295]
Just keeping track. Work not started yet.

Will be included in next release, 1.6.0, which should be released when Django 1.10 is.
Support for Django 1.7 will be dropped at that time.

**Comment by spectras** [comment]
Cleaned up translation deletions, dropping old hacks used with Django 1.4. Will be essential as the new manager API introduced in 1.10 shuffles `_base_manager` and `_default_manager` around a lot. And `_base_manager` is used almost exclusively for deletion.

**Comment by spectras** [comment]
We're almost there. Now I need some input from this ticket: https://code.djangoproject.com/ticket/26749
When the final solution is approved for the issue in that ticket I can complete support for Django 1.10.

**Comment by spectras** [comment]
Support for Django 1.10 is complete. It needs the fix from Django ticket merged into the 1.10 branch before it works completely. The new hvad release will come soon after.

**Comment by claudep** [comment]
The Django ticket is fixed and released in rc1, FYI :-)

**Comment by spectras** [comment]
Thanks! I admit after getting it merged I did not follow the release of Django RCs.
Django 1.10 support is now available on `master` branch. I'll hold the actual release of hvad 1.6 until Django 1.10 is officially released, so I can fix any late incompatibilities, should some arise.

**Comment by claudep** [comment]
I totally understand. In another point of view, releasing before Django final is enticing people to test hvad/django 1.10 in their project and is helping detect incompatibilities missed by the test suite. Chicken and eggs :-)

**Comment by spectras** [comment]
True.
It is possible to test the latest master branch with `pip install https://github.com/KristianOellegaard/django-hvad/archive/master.zip` anytime though.
As the policy is not to push work in progress onto the main branch, it is always stable and somewhat of a rolling RC of the next version.

**Comment by spectras** [comment]
An unexpected incompatibility due to a late bug in Django 1.10 prevents migration at the moment.

Issue #308 will track the evolution of this problem. You may subscribe to that one, I'll update it once it is fixed.

**Comment by spectras** [comment]
Django 1.10.1 and hvad 1.6.0 are out, we should be back to normal.
