### ISSUE TITLE
Django admin form manytomany fields not saved. how to save use django-hvad for translation

### ISSUE THREAD

**Issue by kartikdanidhariya** [KristianOellegaard/django-hvad#296]
I am using dango-cms ==3.2.3, django = 1.8.10

and django-hvad for translation

I have created models.py with many-to-many field. When I add any record in it then it is not show any warning and save record perfectly but when I open that record so it not show many-to-many selected value so I thing many-to-many field is not saved.

my models.py is

```python
class Course(TranslatableModel):
    translations = TranslatedFields(
        domain = models.ManyToManyField('domain.Domain'),
        degree = models.ManyToManyField('degree.Degree', default='1'),
        major = models.ManyToManyField('major.Major', blank=True, null=True),
        course_nm = models.CharField(max_length=100, verbose_name =_('Course Name')),
        code = models.CharField(max_length=10, verbose_name =_('Code')),
        nature_of_training = models.TextField(verbose_name = _('Nature of Training')),
        duration = models.PositiveIntegerField(verbose_name =_('Duration')),
        sem = models.PositiveIntegerField(verbose_name =_('Semester')),
        degree_level = models.CharField(max_length=100, verbose_name =_('Degree Level')),
        credit = models.PositiveIntegerField(verbose_name =_('Credits')),
        locations = models.CharField(max_length=100, verbose_name =_('Locations')),
        title = models.CharField(max_length=512, verbose_name=_('Title')),
        slug = models.SlugField(max_length=512, verbose_name=_('Slug')),
        created_date = models.DateTimeField(auto_now_add=True, blank=True, null=True),
        updated_date = models.DateTimeField(auto_now=True, blank=True, null=True),
        created_by = models.ForeignKey(User,blank=True, null=True, editable=False, related_name='course_user_ceated'),
        updated_by = models.ForeignKey(User,blank=True, null=True, editable=False, related_name='course_user_updated')
    )

    objects = CourseManager()

    def __unicode__(self,):
        return str(self.course_nm)

    def get_absolute_url(self):
        return reverse('course_preview', kwargs={'slug': self.slug})

    def save(self):
        if not self.id:
            self.created = datetime.date.today()
        else:
            self.updated = datetime.datetime.today()
        super(Course, self).save()
```

How can I solve this issue??

**Comment by spectras** [comment]
Hello, thanks for reporting here.

M2M fields are not supported as translatable fields, because it is inherently ambiguous. From your model, it seems this is not needed anyway, as Degree should not be different depending on display language.

More generally speaking, you cannot just dump all of your fields as translated fields, you must split between those for which it makes sense, and those for which it does not.

In some edge cases such as logging translation changes, m2m translated fields might be marginally useful. In that case, refer to https://github.com/KristianOellegaard/django-hvad/issues/284#issuecomment-196777422 for solutions.

**Comment by spectras** [comment]
Hello,
Since I didn't hear back about this issue, I'm assuming you could fix it by changing relevant fields from translatable to non-translatable when it did not make sense. If this is still a problem, please feel free to re-open the issue.

Thanks for taking the time to report here :)
