### ISSUE TITLE
RemovedInDjango110Warning with SQLCompiler in Django 1.9

### ISSUE THREAD

**Issue by callmewind** [KristianOellegaard/django-hvad#300]
Hi, migrating a project from Django 1.8 to 1.9 we get this warning:

`...local/lib/python2.7/site-packages/hvad/manager.py:142: RemovedInDjango110Warning: Calling a SQLCompiler directly is deprecated. Call compiler.quote_name_unless_alias instead.`
`aliases = tuple(qn(alias) for alias in self.aliases)`

Using django-hvad 1.5.1

**Comment by spectras** [comment]
Hello, thanks for reporting here.
That's part of the things that will be addressed by #295. :)
