### ISSUE TITLE
Django 1.10 — notice [updated Sept. 6, 2016]

### ISSUE THREAD

**Issue by spectras** [KristianOellegaard/django-hvad#308]
Hello there,

This is not an issue, but a status notice intended for hvad users.
**[update Sept. 6, 2016: Django 1.10.1 is out and works with hvad 1.6.0. I'll be closing this notice in a few weeks.]**

Support for Django 1.10 **is** implemented, and was planned to be released in hvad 1.6.0, at the time of Django 1.10 release.

However, a [late-found bug](https://code.djangoproject.com/ticket/26997) in Django 1.10 makes it unworkable with hvad (and any other project that has models without default permissions).

The bug has been fixed in Django in commit [a8b8ef](https://github.com/django/django/commit/a8b8ef114dd01d9c1e71a620b732b9aac7b7da5c) on August 2nd, 2016. This fix will be included in Django 1.10.1. It is yet to be released, though.

In the meantime, there are two possible workarounds:
 1. Wait until Django 1.10.1 is released, and upgrade to Django 1.10.1 / hvad 1.6.0.
 2. Use the git version of Django and hvad, that is, https://github.com/django/django/archive/stable/1.10.x.zip and https://github.com/kristianoellegaard/django-hvad/archive/master.zip

As hvad 1.6.0 advertises support for Django 1.10, I chose to postpone its release until Django 1.10.1 is out.
I am sorry for the inconvenience.

**Comment by spectras** [comment]
Django 1.10.1 and hvad 1.6.0 are out, we should be back to normal.

**Comment by spaceexperiment** [comment]
Thanks for the notice, i just upgraded to official django 1.10.1, tested it and it's working fine. Thanks
