### ISSUE TITLE
How do you check for existing translation and update it?

### ISSUE THREAD

**Issue by pushrbx** [KristianOellegaard/django-hvad#309]
I'm trying to update an existing element's translation in the db, but I get "UNIQUE constraint failed" kind of exception, which I think means it tries to add one more translation in the translations table on .save() call. The documentation doesn't have any examples for updating an existing translation.
Could you please show me an example how I would have to update an existing translation?

The model:

    class Person(TranslatableModel):
        name = models.CharField(max_length=255)
        image = models.ImageField(upload_to="images/people", storage=AzureBlobStorage(), blank=True, null=True)
        original_name = models.CharField(max_length=255)
        birthplace = models.CharField(max_length=255, blank=True, null=True) # mal perser doesnt do this
        birthdate = models.DateField(blank=True, null=True)
        link = models.CharField(max_length=255)
        slug = models.CharField(max_length=255)
        published = models.BooleanField(default=True)
        created = models.DateTimeField(auto_now_add=True)
        extsrc_id = models.IntegerField(blank=True, null=True)
        is_incomplete = models.BooleanField(default=True)
    
        translations = TranslatedFields(
            description=models.TextField(blank=True, null=True),
        )
    
        def __str__(self):
            return self.name

My code so far:

    def process_item(self, item):
        people_q = Person.objects.language('en').filter(extsrc_id=item["id"])[:1]
        if len(people_q) == 0:
            return item

        entity = people_q[0]
        entity.name = item["nick_name"]
        entity.original_name = item["family_name"] + item["given_name"]
        try:
            parsed_birthday = parse_profile_date(item["birthday"])
        except ValueError:
            parsed_birthday = "N/A"
        entity.birthdate = parsed_birthday
        entity.description = item["description"]
        # I get exception here:
        entity.save()
        entity.translate('ja')
        entity.description = ""
        entity.save()

        return item

Thanks in advance.

NOTE: I'm using sqlite currently. I haven't tested it with other db engines.

**Comment by pushrbx** [comment]
I've figured it out:

    def process_item(self, item):
        try:
            parsed_birthday = parse_profile_date(item["birthday"])
        except ValueError:
            parsed_birthday = None

        Person.objects.filter(extsrc_id=item["id"]).update(
            is_incomplete=False,
            name=item["romaji_name"],
            original_name=item["family_name"] + item["given_name"],
            birthdate=parsed_birthday,
        )

        Person.objects.language('en').filter(extsrc_id=item["id"]).update(
            description=item["description"]
        )
        Person.objects.language('ja').filter(extsrc_id=item["id"]).update(
            description=""
        )

        return item

The above code works perfectly.
Also I've noticed that 

        Person.objects.language('en').filter(extsrc_id=item["id"]).update(
            is_incomplete=False,
            name=item["romaji_name"],
            original_name=item["family_name"] + item["given_name"],
            birthdate=parsed_birthday,
            description=item["description"]
        )

will only update the translatable fields and the not translatable ones stay unchanged.
Is that an expected behavior?

**Comment by spectras** [comment]
Hello,
Sorry for the late reply. So, here is what happends under the hood:

As stated in the documentation, “the translate() method creates a brand new translation in the specified language”. So you cannot use it to update an existing translation. Thus your original issue. There are two main ways to update a translation:

**1) Load it, change it then save it.** The most intuitive way.
```python
obj = MyModel.objects.language('sr').get(pk=some_id)
obj.some_translated_field = 'Здраво'
obj.save()
```

In case you already have the object, but in another language, the simplest way is to reload it in the language you need:
```python
obj_in_sr = MyModel.objects.language('sr').get(pk=obj_in_en.pk)
```

Granted, it might not be optimal, but it's the fastest way to write it, and requires the least understanding of hvad. Alternatively, if you know you will be using several translations, you can get them all in one query, like this:
```python
translations = MyModel.objects.language('all').filter(pk=some_id, language_code__in=('en', 'ja'))
```
Just remember that when doing this, untranslated field are *not* shared, each instance in `translations` has a separate copy of them.

**2) Generate an update query manually like you did in your second post.** By the way, the sample you posted should work, that is: 

```python
    Person.objects.language('en').filter(extsrc_id=item["id"]).update(
        is_incomplete=False,
        name=item["romaji_name"],
        original_name=item["family_name"] + item["given_name"],
        birthdate=parsed_birthday,
        description=item["description"]
    )
```
This should work, updating all fields in the database. There is even a [test case](https://github.com/KristianOellegaard/django-hvad/blob/master/hvad/tests/query.py#L223) for this specific example.
However, remember that, as usual with Django, any objects that you loaded before that query will retain the old values, you need to reload them from the database if you want them to reflect the new values.

This might get a bit confusing with hvad, as hvad will reload translations automatically in certain circumstances, which, in this specific corner case, gives you an object that has the new database values loaded in its translated fields, and old values lingering in its untranslated fields.
