### ISSUE TITLE
fallback confusion

### ISSUE THREAD

**Issue by patroqueeet** [KristianOellegaard/django-hvad#310]
dear,

I'm about to upgrade to latest hvad. but I'm confused with replacing my fallback logic.

currently I do the change alike:
```
-            company = Company.objects.untranslated().get_fallbacks(
-                *fallback_priority()).get(slug=company_identifier)
+            company = Company.objects.untranslated().get(slug=company_identifier)
```

is this correct? it does not require the `*fallback_priority()` anymore? and as `untranslated()` returns a `SelfJoinFallbackQuerySet` the `fallbacks()` call is also not required anymore?

**Comment by spectras** [comment]
Hello!
There has been a change in the fallbacks logic over hvad versions indeed. Here is a short history:

  * First implementation used a wrapper to automate subqueries. Automation was a nice feature, but queries with many results generated many queries (roughly 1 additional query for every 100 rows).
  * Then hvad 0.5 introduced a better way to handle fallbacks, using a custom JOIN clause, drastically reducing the number of queries. That what `SelfJoinFallbackQuerySet` is about.
  * After manager evolutions in hvad 1.1, the features from `SelfJoinFallbackQuerySet` were merged into the main manager. The API was also clarified to the way it currently is.

So here is today's state:
  * `MyModel.objects.untranslated()` is intended for getting untranslated instances. Without fallbacks. As a matter of fact, ̀.unstranslated().use_fallbacks()` is not supported on Django 1.9 and newer.
  * For fetching translated instances, use `.language()`.
  * If fallbacks are wished for, simply add `.fallbacks()` after `.language()`.

For instance:
```python
# Load object without any translation
untranslated = Normal.objects.untranslated().get(pk=42)
untranslated.some_translated_field    # will try to load translation from the database

# Load object in English. Will fail if object is not available in English
translated = Normal.objects.language('en').get(pk=42)

# Load object in English. Will fallback to French, then Serbian, then whatever is available.
translated = Normal.objects.language('en').fallbacks('fr', 'sr').get(pk=42)
```

If you have translation-aware code, you may also be interested in the possibility of loading all translations as a queryset:
```python
all_translations = Normal.objects.language('all').filter(pk=42)

# You can then do, for instance:
as_dict = dict((item.language_code, item) for item in all_translations)
as_dict['en']   # will return the English version of the object, if there is one
```
This returns a queryset with as many copies of the object as there are available translations, each copy being loaded with a translation. Keep in mind copies are independent, changing an untranslatable field on one copy will not update the other copies, it's mainly intended for manipulating translations.

I hope it helps, feel free to ask if you need any help.

**Comment by spectras** [comment]
Assuming the answer was enough, feel free to reopen or create other tickets if needed.
