### ISSUE TITLE
Add support for only() and defer()

### ISSUE THREAD

**Issue by barseghyanartur** [KristianOellegaard/django-hvad#312]
Are there plans to implement support of `only` and `defer`?

**Comment by spectras** [comment]
As I am very very low on time, it's not planned. In fact for the next few months, don't expect more than regular maintenance: fixing bugs and supporting new Django versions.
That said, it would be great to have it, if someone feels like looking into it.

**Comment by barseghyanartur** [comment]
I would at least mention that in the documentation. In the very first paragraphs - Limitations. So that devs are aware what are they going to deal with.

**Comment by spectras** [comment]
To be fair, when hvad started it would have had all Django features in "limitations". Including feature combinations, and there are lots of those (recently a bug was opened for a regression in combining `.select_related()` with `.values_list()`).
It grew slowly, features being implemented over time as they were requested (or sometimes pull requests got opened).

Not much has changed, only those days I am the only active maintainer and I have extremely little time at the moment. This is in the feature requests, it will get implemented eventually. I just cannot give a deadline without making it up and probably missing it.

**Comment by spectras** [comment]
As a sidenote, I have a working implementation of `only()` and `defer()` for Django 1.8 and newer. It needs proper testing, but it will probably make it in v1.7.

**Comment by spectras** [comment]
As a sidenote, I have a working implementation of `only()` and `defer()` for Django 1.8 and newer. It needs proper testing, but it will probably make it in v1.7.

**Comment by barseghyanartur** [comment]
That would be awesome! Thank. Much appreciated.

**Comment by spectras** [comment]
Initial support is now on `master`.
But as a restriction, it only supports the first level for now. That is, `.select_related('some_relation').only('some_relation__some_field')` does not work yet.

**Comment by barseghyanartur** [comment]
I'm recently working on a performance optimisation of a project which uses hvad. It contains insane amount of huge sql queries (>500 per page). Part of it comes from hvad and by far, there are very few places where fetching of all database columns it's needed. Therefore, fetching only columns that are required is part of the optimisations. I don't know what other issue's are on the priority list (is there a roadmap?), but this one is one of the widely applicable, essential features, that hvad users would need, I think.

**Comment by spectras** [comment]
There is no *roadmap*, but #249 and #273 give a pretty good picture of what I would like the future of hvad to be. Especially #273 is a major refactor that would change the way queries are altered, leveraging Django's ORM evolutions to lift the biggest restriction of hvad: its inability to work with joins (`.filter(some_model__translatable_field="foo")`). For filtering it's easy to workaround (manually add an intermediate `__translations` and filter on language code), but it's cumbersome and is plain impossible to do for some other methods.
Also, that would enable reverse managers on relations to translatable models to work seamlessly. And probably solve many issues with admin.

For 1.7.0, I would like to fix the other lingering bugs and suppress the old deprecation exceptions.

You may also install current master using `pip install https://github.com/KristianOellegaard/django-hvad/archive/master.zip`. Right now, it's exactly v1.6.0 with this feature added and bug #319 fixed.

**Comment by spectras** [comment]
Version 1.7.0 is here now.
