### ISSUE TITLE
Setting __all__ in fields raises a FieldError

### ISSUE THREAD

**Issue by czpython** [KristianOellegaard/django-hvad#313]
Django allows forms to define `fields = '__all__'` to avoid listing all fields in the model, unfortunately this causes the following error:

```
django.core.exceptions.FieldError: Unknown field(s) (a, l, _) specified for HvadModel
```

**Comment by urtzai** [comment]
+1

**Comment by spectras** [comment]
Definitely. Looks not too hard to add and worth the trouble for ensuring APIs match.
No ETA though, I am in the middle of Turkey posting from a cybercafe right now.

**Comment by czpython** [comment]
Take your time my friend, enjoy Turkey :)

**Comment by spectras** [comment]
Fixed on master.
As a sidenote, not setting `fields` at all, or setting `fields = None` used to have exactly the same result. The `__all__` thing is a recent addition do Django. And what Django does with it is pretty straightforward: `if meta.fields == '__all__': meta.fields = None`.
