### ISSUE TITLE
Cannot delete translations in the admin

### ISSUE THREAD

**Issue by orf** [KristianOellegaard/django-hvad#317]
Hi,
I've got a model with a string `pk`, e.g `com.test.app`. I can no longer delete translations within the admin, because inside [delete_translation](https://github.com/KristianOellegaard/django-hvad/blob/923cff93527693ab0e603c42861bf6c2836b4da0/hvad/admin.py#L205) the `object_id` parameter is `'com.test.app/change'`, where I think it should just be `com.test.app`.

This triggers the `raise Http404` error.

**Comment by spectras** [comment]
Hello,
Thanks for reporting. I am very, very low on time until the beginning of December, at which point I'll have some time for hvad again. I will try to see fixing it before, but no promises.

**Comment by spectras** [comment]
I gave it a go last night, and was not able to reproduce the bug. Could you please show me a sample of your model / admin that exhibits the bad behavior? Thanks!

**Comment by michalkaspar** [comment]
Hi,
I have a same issue. I see problem in this code:

`return [
            url(r'^(.+)/delete-translation/(.+)/$',
                self.admin_site.admin_view(self.delete_translation),
                name='%s_%s_delete_translation' % info),
        ] + urlpatterns
`

Variable object_id is there whole url before /delete-translation/ which contains also '/change' part.

**Comment by spectras** [comment]
Hello! Excellent catch.
Though I still don't understand how comes the `/change` part ends up before `delete-translation`.
Does it happend when you click the _"Delete Translation"_ link on the change page, or when you confirm deletion in the subsequent page?

**Comment by michalkaspar** [comment]
It happens when i click on "Delete Translation" link in change page.

**Comment by spectras** [comment]
Thanks. Could you also tell me whether:

 * The delete translation link has the `/change` part before `delete-translation`?
 * The change page itself has the `/change` part doubled?

Also, just to be sure I'm testing with the right version, can you tell me which Django version you run?

**Comment by michalkaspar** [comment]
Thanks for quick response,

my url looks for example like: `.../5263/change/delete-translation/cs`

I'm using python 3.5 and django 1.10.4.

**Comment by spectras** [comment]
Thanks to you.
Well, that url is incorrectly generated. I'll try to see why…

**Comment by spectras** [comment]
I think found the culprit. A sub-template generates dumb relative urls. Not a problem with numeric pk as the `/change` part just gets discarded, but troublesome with string pks obviously. Fix going through travis testing now.

**Comment by spectras** [comment]
Issue should be fixed on master. You can try it using `pip install https://github.com/KristianOellegaard/django-hvad/archive/master.zip`.
