### ISSUE TITLE
Support for deep copy of hvad TranslatableModel

### ISSUE THREAD

**Issue by val-rog** [KristianOellegaard/django-hvad#320]
I am not sure that creating issue is the best way to ask the question, but anyway:

Django supports an easy way to create the deep copy of model: simply set id to None and then save. But also it's declared that foreign relations are not copied (e.g. hvad translations, as far as hvad uses separate table for translations).

What is the best way to get deep copy of hvad model and its translations?

Thanks :)

**Comment by spectras** [comment]
For a single model in current translation, simply set its pk to `None` and currently loaded translation will be copied.
For copying all translations, you should load them and duplicate them in the same way. I cannot test right now, but something along those lines should do:

```python
translations = obj.translations.all()
obj.pk = None
obj.save()
for translation in translations:
    translation.pk = None
    translation.master = obj
    translation.save()
```
Not very optimal, you could do a bulk_create instead, but that's the idea.

**Comment by val-rog** [comment]
Thanks for answer! I tried this way, but got exception on obj.save() call.

The problem is that I've overriden the save method to modify object's name a little:
```
def save(self, *args, **kwargs):
        self.name= util.normalize(self.name) 
        super().save(*args, **kwargs)
```

And the exception is thrown at execution of self.name:
```
File "C:\Soft\Python35\lib\site-packages\hvad\descriptors.py" in __get__
  51.        return getattr(self.translation(instance), self.name)
File "C:\Soft\Python35\lib\site-packages\hvad\descriptors.py" in translation
  27.                                                'loadable from the database' % get_language())
Exception Type: NoTranslationError at /admin/duplicate_model/
Exception Value: Accessing a translated field requires that the instance has a translation loaded, or a valid translation in current language (ru) loadable from the database
```

How can I solve this problem? I really need this normalization to be done in save() method :)

**Comment by spectras** [comment]
You might want to check a translation is actually loaded before changing translated fields in your `save` method then. The best way to do this is:
```python
from hvad.utils import get_cached_translation

translation = get_cached_translation(self)
if translation is not None:
    self.name = util.normalize(self.name)
super().save(*args, **kwargs)
```

**Comment by val-rog** [comment]
Completely works, thank you!
