### ISSUE TITLE
Order_by on translatable ForeignKey

### ISSUE THREAD

**Issue by rzych** [KristianOellegaard/django-hvad#323]
Hello, I'm not sure if this is a bug (maybe I'm doing something wrong) 

I don't know how to access to language manager from order_by method. To the point:

I have simple models:
```

`class DescModel(TranslatableModel):
    translations = TranslatedFields(
        description=models.TextField()
    )

    class Meta:
        abstract = True`

`class ModelA(DescModel):
    translations = TranslatedFields()`

`class ModelB(TranslatableModel):
    translations = TranslatedFields(
        tr_model_a=models.ForeignKey(ModelA)
    )`
```

and then from shell:

`r = ModelB.objects.language('pl').all()`

but when I'm trying this:

r.order_by('tr_model_a__name') 

I get:

> To access translated fields like 'name' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method

Little update:

I've used: get_translation_aware_manager

`m = get_translation_aware_manager(ModelB) `

and this works!

`m.order_by('tr_model_a__name')`

but this:

`m.order_by('-tr_model_a__name')`

gave me an error:
 

> To access translated fields like 'tr_model_a' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method.

I tried without minus and reverse method but it is not implemented

**Comment by spectras** [comment]
Hello,

Thanks for taking the time to report here. Hmm, that exception message is confusing, I'm planning to get rid of it at some point. Here, you don't need `get_translation_aware_manager`, that is intended to give translation-aware functionality to a regular, untranslatable model.

The issue you have is `hvad` does not support deep query translation yet. That is, referring to translatable fields of a related model in a query is unsupported (support is planned for hvad2).

I did not test it, but I believe a workaround could be to build the query manually, a bit like this:

```python
r = ModelB.objects.language('pl').filter('tr_model_a__translations__language_code='pl').order_by('tr_model_a__translations__name')
```

I am not sure this will work though. It depends on whether `order_by` will re-use the JOIN generated by `filter` or create a new one. I believe it will but I am not sure so, if you can post the generated query here, I can easily tell you if it is the case or not.

**Comment by spectras** [comment]
Closing inactive issue. Feel free to re-open should you need it.
