### ISSUE TITLE
error while updating to 1.6.0

### ISSUE THREAD

**Issue by superzazu** [KristianOellegaard/django-hvad#325]
Hello!

Recently with my team, we upgraded django-hvad to the latest version (1.6.0). But now, everytime we do a `makemigrations`, we get something like this:
```
You are trying to change the nullable field 'master' on announcementtranslation to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
 3) Quit, and let me add a default in models.py
Select an option:
```

On a bunch of TranslatableModels. I looked in the docs, but I didn't find anything concerning this kind of problem. How should we proceed to avoid these errors ?

Thank you

**Comment by spectras** [comment]
You should just entre `2` everytime this question is asked.
If the migration then fails (unlikely but can happen), it means you have some left-over translations with no objects attached, you should delete them. From this point forward, this cannot happen anymore, and the NOT NULL constraint will enforce it for the better.

**Comment by superzazu** [comment]
Thank you for your answer, that was it! :-)

**Comment by spectras** [comment]
Great! I'm closing as resolved. Feel free to open again should you need it. Otherwise I wish you a happy new year !
