### ISSUE TITLE
Enable fallbacks for all models

### ISSUE THREAD

**Issue by val-rog** [KristianOellegaard/django-hvad#327]
Hello! First of all thank you for the great project! It really helps to seamlessly create and use models in different languages. 

Now, the question :) 

There are a lot of TranslationModel-s in my app and I need to enable fallbacks to default languages (taken from settings.LANGUAGES) for all of them.

After rtfm-ing I came to the following, a bit ugly solution:

```
class FallbackTranslationQuerySet(manager.TranslationQueryset):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fallbacks()
```
... and then for each model:

```
class YetAnotherModel1 (TranslatableModel):
    objects = manager.TranslationManager(default_class=FallbackTranslationQuerySet)
    ...

class YetAnotherModel2(TranslatableModel):
    objects = manager.TranslationManager(default_class=FallbackTranslationQuerySet)
    ...

...
```

Maybe there is some more clean solution?

Thanks!

**Comment by spectras** [comment]
Hello ! Sorry for the delay, I'm on holidays right now. I will get back to you when I'm back home.

**Comment by spectras** [comment]
Hello again!

Well, `fallbacks()` does not modify current queryset, it returns a new one with fallbacks enabled. So your custom queryset actually does nothing more than regular TranslationQueryset.

There is no built-in way to "blanket"-add fallbacks to all querysets, because fallbacks do not work with all queries. That being said, you can make one the normal django way:

```python
class FallbackTranslationManager(TranslationManager):
    def get_queryset(self):
        return super(FallbackTranslationManager, self).get_queryset().fallbacks()
```
You'll need to add it manually to all concerned models the way you did. I would discourage you from using such a manager as the default manager though, as it violates Django rules (it may not show some objects in some circumstances).

I wish you a happy new year.

**Comment by spectras** [comment]
Closing now, feel free to re-open this, or open another issue as appropriate should you need to.

**Comment by val-rog** [comment]
Hello! :)
Happy new year too :) I was offline for a long time, just returned.

Thans for your reply. I will describe my situation and ask you for advice.

My app is very simple: I have a lot of DB entities that are displayed in UI. All of them are in Russian. In order to preserve the opportunity to have English (or any other) translations I use django-hvad.
The problem appeared when people tried to access my site from en-us locale. Django-hvad tries to find corresponding en-us translation and fails because there are only the ru ones.

So all I want is to give a directive to hvad: "please, consider 'ru' as default language. If you fail to find some translation - use the 'ru' one." Of course I want to leave a room for further i10n, so I need to list these default languages: "first try to find the translation with user's locale, than (if failed) - the 'en' one, and then finally the 'ru' one".

I guess fallbacks are suited just for that so I came to the solution from my 1st post. Btw, you say that it would not work, but basically it works perfect: I enable fallbacks for TranslationQuerySet via executing 'self.fallbacks()' from constructor and then use it in all TranslationManager-s. If I use standard TranslationQuerySet, users get an error ('translation for en-us does not exist) while if I use the modified one, everything is OK: they obtain 'ru' translation via fallbacks mechanism.

Your solution seems to be similar to mine (I extend the queryset and substitute defaultclass to translation manager - you do the same via extending translation manager itself), so we are finished with question from my opening post :)

**Comment by val-rog** [comment]
Now the new questions:

1. I really need to use fallbacks 100% of time. Why shouldn't I? Can you please explain it more detailed?
2. There is one use case where using TranslationQueryset is inappropriate for me. Sometimes I need to duplicate the entity with translations (i.e. make full deep copy of entity+foreign relations). I do it by setting pk to None (as you recommended in [issue 320](https://github.com/KristianOellegaard/django-hvad/issues/320)). If I use my FallbackTranslationQuerySet, translations are not copied but relinked to new entity and the old one loses them.
So I guess I need the following:
- always use the fallbacks query set
- sometimes have an opportunity to use the usual one.

What's the best way to do it?

Sorry for verbosing, hope for reply. This problem (translations are relinked, not copied) really drives me mad :(

**Comment by spectras** [comment]
1) the fallback version of the queryset might not return some records. Namely, if some records have no translation at all, the will be hidden by the queryset. This violates Django conventions, which clearly states the default manager of a model **must** not hide model instances.

I don't know what the consequences would be should you do it anyway. I guess as long as you don't *have* any model instance with no translation you would be fine. Such instances are considered buggy anyway so you might be ok, but be aware that those buggy instances will be harder to spot if they don't show up at all.

2) that's odd, can you post the code you use for this here?
