### ISSUE TITLE
403 CSRF error django admin 1.10

### ISSUE THREAD

**Issue by sonic182** [KristianOellegaard/django-hvad#328]
Hi, I'm having this issue trying to remove a translation!

Stack:
django>=1.10.3, <1.11 (1.10.4 at this moment)
django-hvad==1.6.0
Python 3.5

![image](https://cloud.githubusercontent.com/assets/4070466/21522743/7b92fd0e-cd08-11e6-9c86-8e70785a62be.png)

![image](https://cloud.githubusercontent.com/assets/4070466/21522731/68d39bec-cd08-11e6-9a1a-991ca5f23cf0.png)

![image](https://cloud.githubusercontent.com/assets/4070466/21522734/6eb653ec-cd08-11e6-9394-def6ff5fb974.png)

I have all setted up correctly, I saw the source-code of **delete-translation** view and it doesn't have the hidden token. I think It's a django admin issue instead of here but just in case of.

Best
Johanderson

**Comment by spectras** [comment]
Hello ! Thanks for reporting. I'm on holidays right now. I'll get back to you when I'm back home. In the meantime I wish you a happy new year !

**Comment by spectras** [comment]
Hello again!

I am not certain what causes this, but the admin is using the old version of the Django rendering API right now. I will update it to use the new (Django 1.8+) rendering path and see if the issue persists.

**Comment by sonic182** [comment]
I did use Django 1.10 and had that issue so it should persist :/

**Comment by spectras** [comment]
Sorry, I mean **hvad** is using the old rendering path. But a new one exists, and I am updating hvad so it uses it intead of the old one.

Can you try this patched version of hvad to see whether the problem persists? 
```pip install https://github.com/spectras/django-hvad/archive/master.zip```

**Comment by spectras** [comment]
Patch is now part of hvad 1.7.0, and should have fixed this issue. Closing it now.
