### ISSUE TITLE
Problem saving translation for translated model with MPTT

### ISSUE THREAD

**Issue by cisarpavel** [KristianOellegaard/django-hvad#329]
Hi, I've got simple models structure

```
class Page(MPTTModel, TranslatableModel):
    name_of_url = models.CharField(max_length=100, unique=True, verbose_name=_('admin-url_unique_name'), help_text="Example: 'about-contact'. No spaces allowed.")
    menu_parent = TreeForeignKey('self', null=True, blank=True, limit_choices_to= { 'menu__isnull' : False, 'menu_parent__isnull': True}, related_name="children", verbose_name=_('admin-page_assigned_menu_parent'))
    menu_order = models.PositiveSmallIntegerField(default=99, verbose_name=_('admin-page_order_in_menu'))
    template = models.PositiveSmallIntegerField(default=1, choices=choices.PAGE_TEMPLATE_CHOICES, editable=False, verbose_name=_('admin-page_template'))

    translations = TranslatedFields(
        url=URLPathField(max_length=100, blank=True, help_text="Example: 'about/contact/'. Make sure to have trailing slashes.", default=''),
        title=models.CharField(max_length=200, blank=True, default='', verbose_name=_('admin-title')),
        h1=models.CharField(max_length=200, blank=True, default='', verbose_name=_('admin-h1')),
        description=models.CharField(max_length=255, blank=True, default='', verbose_name=_('admin-meta_description')),
        keywords=models.CharField(max_length=255, blank=True, default='', verbose_name=_('admin-meta_keywords')),
        content=models.TextField(blank=True, default='', verbose_name=_('admin-content')),
    )
```

Generally hvad and mptt works fine together, but problem is when saving some changes in translated fields without changing mptt order. In such case mptt prefills `update_fields` kwargs ([src](https://github.com/django-mptt/django-mptt/blob/master/mptt/models.py#L964)) with translated model field names, but not with names of translated fields and so hvad does not save translation for translated model [src](https://github.com/KristianOellegaard/django-hvad/blob/master/hvad/models.py#L272), because it thinks that none of translated fields is updated.

**Comment by cisarpavel** [comment]
Btw, hot fix seems to be changing order of model ancestors. TranslatableModel to be the first and MPTT after, but it seems to me quite labile solution.

**Comment by spectras** [comment]
Hello, thanks for reporting.
Well, hvad does not really care whether it is first, or last, or somewhere in between.
However, as it routes translated and untranslated fields to their respective model, order does have an implication. Namely, anything put *before* `TranslatableModel` will have access and control on all fields. Anything after will only see and control untranslated fields. That's the whole point of hvad: allowing your own models to see translated and untranslated fields homogeneously.

Changing the order might be a solution. Altenately, you could also override MPTT's `_get_user_field_names()` so it returns translated fields as well.
