### ISSUE TITLE
Error in admin 'XTranslation' object has no attribute 'translate'

### ISSUE THREAD

**Issue by Cediddi** [KristianOellegaard/django-hvad#334]
Hi. I recently upgraded my django 1.8 project to 1.11 as well as hvad 1.6 to 1.7. After the upgrade, I'm having an issue in admin page.

When TranslatableAdmin calls get_object, it first calls get_queryset. For django 1.9+ get_queryset returns a queryset with Translation objects. After having the queryset, get_object method gets the object from queryset by id. Until now, everything looks fine but, then the code checks if request's language is same to object's language and if they are not the same, the code calls obj.translate(request_lang). Problem is, get_queryset returns Translation objects, not the main model's objects and Translation objects does not have translate methods. Thus this code shouldn't work at the first place. What am I missing? Also is there an ETA for hvad2 or Django1.11 support?

**Comment by spectras** [comment]
Hello,
Thanks for reporting!

Indeed django 1.11 is not yet supported. Initial work was done about 3 months ago, but several changes were added to Django before the release, which current hvad version does not account for.
I have been pretty busy, so I did not follow the exact schedule and was not aware 1.11 was out. I'll complete compatibility fixes and publish a new release within 5 days. In the meantime, Django 1.10.x (with x >= 1) should work.

As for hvad2, it has no ETA, as some pieces don't fit well with Django and I want to wait until I have a better view of Django 2 architecture before committing more to a design choice. In the meantime, I'll continue to maintain hvad1.

**Comment by Cediddi** [comment]
Support for 1.11 would be great. I'd be glad to help for it.

**Comment by Cediddi** [comment]
Comment for anyone finds this issue. I got a walkaround!

I did something wicked, I imported auto created Translation models (despite pycharm warning me).  I created inlines for those auto created models and added them to admin page. Below is an example code:

    # models.py
    from hvad.models import TranslatableModel, TranslatedFields
    from django.db import models
    
    
    class State(TranslatableModel):
        name = models.SlugField(unique=True)
    
        translations = TranslatedFields(
                label=models.TextField()
        )
    
    
    # admin.py
    from django.contrib import admin
    from django.conf import settings
    from .models import State
    from .models import StateTranslation  # This is where the black magic happens and you import the auto created Translation model
    
    
    class StateTranslationInline(admin.StackedInline):
        model = StateTranslation
        max_num = len(settings.LANGUAGES)
    
    
    @admin.register(State)
    class StateAdmin(admin.ModelAdmin):
        inlines = [StateTranslationInline]

Don't forget to sacrifice a cup of coffee to elder gods before doing such hacks 😄

**Comment by spectras** [comment]
Hello again!

Well, first I'm glad you found a workaround. I'm looking into the main issue.
I see I actually did the bulk of the work on compatibility 2 months ago but, while waiting for the release to come out, they just sit in the master branch. Running the master branch against Django 1.11 triggers no test failure.

Could you try the `master` branch and tell me whether it works for you?

**Comment by Cediddi** [comment]
I'll try master today. Also thanks for the tip 👍

**Comment by spectras** [comment]
New release is out, can be more convenient that master for testing.
I believe the problem should no longer be there, but it would great if you could confirm that.

**Comment by Cediddi** [comment]
Yeah, this works great. Sorry for late reply :)

**Comment by spectras** [comment]
No worries, thanks for the feedback :)
