### ISSUE TITLE
TypeError in BaseTranslationFormSet when creating language_code widget 

### ISSUE THREAD

**Issue by grote** [KristianOellegaard/django-hvad#335]
When using a `FormSet` generated from a `translationformset_factory`, I get this stacktrace:
```
  File "/home/user/.local/lib/python3.5/site-packages/django/forms/models.py", line 604, in _construct_form
    return super(BaseModelFormSet, self)._construct_form(i, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/django/forms/formsets.py", line 183, in _construct_form
    self.add_fields(form, i)
  File "/home/user/.local/lib/python3.5/site-packages/hvad/forms.py", line 334, in add_fields
    widget=Select(choices=(('', '--'),)+settings.LANGUAGES)
TypeError: can only concatenate tuple (not "list") to tuple
```
The line in question 
```python
widget=Select(choices=(('', '--'),)+settings.LANGUAGES)
```
should probably be replaced with:
```python
widget=Select(choices=[('', '--'),]+settings.LANGUAGES)
```

**Comment by spectras** [comment]
Hello,
Thanks for reporting! Despite Django documentation examples using a list, most people have their `settings.LANGUAGES` as a tuple actually. Which makes sense, as this setting cannot be reliably changed after Django initialization.

Yet I agree, having it raise an exception when following Django documentation is not right. I'll probably do something like this so it works in both cases: `choices=(('', '--'),)+tuple(settings.LANGUAGES)`.

Next release will split hvad settings from Django settings, solving this issue in a cleaner manner anyway.
Have to keep a tab on this though, to make sure it's not subject to the same caveat.

**Comment by grote** [comment]
Thanks for responding so quickly (and of course for maintaining this great library)!

Just a minor addition for sake of completeness: This is not only when following the Django [documentation](https://docs.djangoproject.com/en/1.11/ref/settings/#languages), but also when not touching `settings.LANGUAGES` at all, because [the default value uses a list](https://github.com/django/django/blob/d7b9aaa366dd54ecc3142c588162e3adc7c2f7ac/django/conf/global_settings.py#L56) as well.

**Comment by spectras** [comment]
Should no longer be an issue in new release. Could you please confirm?

**Comment by grote** [comment]
Thanks, that fixed it for me!
