### ISSUE TITLE
Using hvad in a DRF filter 

### ISSUE THREAD

**Issue by jinpark** [KristianOellegaard/django-hvad#339]
I have a bunch of views using DRF that include something like this. 

The code within `get_queryset` is where the hvad code is

```
class CollectionsRetrieveUpdate(generics.RetrieveUpdateAPIView):
    def get_queryset(self):
        language = self.request.query_params.get('language', settings.LANGUAGE_CODE)
        return Collection.objects.language(language).fallbacks('en-us').all()
    serializer_class = CollectionSerializer
```

I was wondering if I could DRY that up by removing the language/hvad code and putting it into a filter like this 

```
class TranslationFallbackFilter(filters.BaseFilterBackend):
    def filter_queryset(self, request, queryset, view):
        language = request.query_params.get('language', settings.LANGUAGE_CODE)
        return queryset.language(language).fallbacks('en-us')
```

but I get an error of something similar to 

`AttributeError: 'QuerySet' object has no attribute 'language'`

Do I need to use a custom manager to make this work or is there an hvad suggested way to do this?

**Comment by spectras** [comment]
Hello,

You should be able to just put it in a filter like you did, but only if the queryset it is passed is translation-aware queryset. This is what you should get by specifying it on your view:

```python
class CollectionsRetrieveUpdate(generics.RetrieveUpdateAPIView):
    queryset = Collection.objects.language()
```

This will make DRF's default `get_queryset()` return a translation-aware queryset.
Actually, if your backend uses django's `LocaleMiddleware`, then the language will be automatically set to the request's detected language (see here [Django's language detection](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#how-django-discovers-language-preference). Most notably, assuming you use separate domains for your main site and your API, you can use HTTP header `Accept-Language` from your frontend.

**Comment by jinpark** [comment]
Thanks for the info! 

I'll restructure my code to match your advice!
