### ISSUE TITLE
Views for TranslationsMixin

### ISSUE THREAD

**Issue by danilke** [KristianOellegaard/django-hvad#341]
I have model `Product`:

    class Product(TranslatableModel):
        name = models.CharField(max_length=255, unique=True)

        translations = TranslatedFields(
            description=models.TextField(),
        )

 and in administration on product detail I have tabs with languages. For example tabs EN, CZ, each includes `disctiption`. So PUT request looks like: 

    {
        'product': '1',
        'id': 1,
        'name': 'Name', 
        'translations': {
            'cz': {'desctiption': 'Description cz'},
            'en': {'desctiption': 'Description en'}
        }
    }

I have found in [django-hvad TranslationsMixin][1] that allows me to do that request. 

In serializers I have:

    class ProductTranslationSerializer(serializers.ModelSerializer):
        class Meta:
            exclude = ['description']

    class ProductSerializer(TranslationsMixin, serializers.ModelSerializer):
        class Meta:
            model = Product
            translations_serializer = ProductTranslationSerializer
            fields = (
                'name', 
                'description',
            )

Question is how will looks ModelViewSet for this request? Can I choose language like 'language_code=en', filter that query and get something like:

    [
        {
            id: 1
            name: "name"
            descritpion: "descritpion"
        },
        ....
    ]

Thank you!

  [1]: http://django-hvad.readthedocs.io/en/latest/public/restframework.html#translationsmixin

**Comment by spectras** [comment]
Hello,
If I understand well, you want to use a different serialized form for the collection endpoint and the item endpoint. That is, `GET`-1, `PUT`, `POST` would use the translations mixin, while `GET`-many would not.
You need two have two different serializers for this:
* The one you created
* another one that would be, for instance,<br> `class ProductItemSerializer(TranslatableModelSerializer): ...`

Given that, you can add to your ModelViewSet a method that dynamically chooses the serializer class depending on request type:
```python
class SomeModelViewSet(ModelViewSet):
    # serializer_class = not needed, we use the method instead
    def get_serializer_class(self):
        if self.action == 'list':
            return ProductItemSerializer
        return ProductSerializer
```

**Comment by danilke** [comment]
Hello, thank you for usefull information!

**Comment by danilke** [comment]
I have one more question. with class ProductSerializer(TranslationsMixin, serializers.ModelSerializer): I got error: 

> Accessing translated fields like product.name_1 from an regular model requires a translation-aware queryset, obtained with the .language() method. For regular, non-translatable models, you can get one using hvad.utils.get_translation_aware_manager

Product is TranslatableModel. Why does it happens? Thank you.

**Comment by spectras** [comment]
That would depend on what you do with the model and/or the query.
Can you post your serializer/viewset?

**Comment by danilke** [comment]
Sorry, my falt,  find error :|
