### ISSUE TITLE
What about a default language for untranslated fields?

### ISSUE THREAD

**Issue by igorsantos07** [KristianOellegaard/django-hvad#346]
In the current HVAD implementation we can only show objects with the current language (through `XYZModel.language().all()` or similar), or select a specific language. In cases where not all models were translated in any given language, we end up with an incomplete list of entries in different languages.

What we wanted, instead, was having a default language - i.e., if we're selecting models in Portuguese but some only had English text, please bring English anyway, it's still better than not showing info at all.

I didn't want to mess with HVAD code as I'm a Python/Django newbie and the project seems quite closed (does what it does in a magical way and does it well but leaves almost no space for custom implementations).

So, with this I am:
1. asking if this feature makes sense, and maybe hope for an implementation of it for future users;
2. ask an opinion on this signal received I wrote to "force-translate" so our models are never missing in some language (and leaving it if anyone else needs something like this):

```python

DEFAULT_LANGUAGES = ('pt-br', 'en')
IGNORABLE_FIELDS = {'id', 'master', 'language_code'}
force_translating_now = []  # helps avoiding infinite loops when saving translations

@receiver(post_save)
def set_default_for_missing_translations(sender, **kwargs):
    if issubclass(sender, TranslatableModel):
        model = kwargs['instance']
        if model in force_translating_now:
            return  # already being processed - this got triggered when saving a translation, so we can just skip

        ready = model.get_available_languages()
        if len(ready) == 0:
            # we have nothing yet... is it missing fields or just a model eager to be saved?
            force_translating_now.append(model)
            model.save()
            ready = model.get_available_languages()
            force_translating_now.remove(model)
            if len(ready) == 0:
                return  # yep, nothing found, let's just move on

        missing = []
        for (lang, name) in settings.LANGUAGES:
            if lang not in ready:
                missing.append(lang)
        print("Missing for %s: %s" % (model.__class__, str(missing)))

        default = None
        for default_lang in DEFAULT_LANGUAGES:
            if default_lang in ready:
                default = default_lang

        if default is None:
            return  # we are hopeless, no default language is available

        # storing this model in the "in process" list, so when we save a translation this function isn't triggered again
        force_translating_now.append(model)

        # getting a base translation and shoving its fields into each missing language of this model
        base = model.translations.get(language_code=default)
        fields = set(f.name for f in base._meta.get_fields()) - IGNORABLE_FIELDS
        for new_lang in missing:
            translation = model.translate(new_lang)
            for field in fields:
                setattr(translation, field, getattr(base, field))
            translation.save()

        # alright, we're done here, we can remove this model from the "in process" list
        force_translating_now.remove(model)
```

**Comment by spectras** [comment]
Hello!

How about `XYZModel.language().fallbacks('pt-br', 'en')` ?
That will pick the first available translation from that of `language()` or any fallbacks.
It doesn't create them in the database, rather it performs the query on all those languages at once.

**Comment by igorsantos07** [comment]
Is that documented anywhere? 🤦‍♂️ 

Yes, it is, in the Queryset API page. Sad I spent hours writing this because I didn't see that suggested in quickstart or models doc. It's certainly missing from the QuickStart, and missing some sample code as well 😞
