### ISSUE TITLE
Select object even if a translation doesn't exists

### ISSUE THREAD

**Issue by Que-20** [KristianOellegaard/django-hvad#347]
Hello,

I'm doing an e-commerce website and I have a problem.

I have products which have a description : this description can be in several languages and can to be optional. What I would like to do is if a product don't have a description in a specifical language, I would still like to retrieve others information, except that for the moment, if this product don't have a translated description, no result are returned. In brief, I would like to do a "left join" instead of "inner join" but I don't found anything for to do that.

Thank you in advance.

**Comment by spectras** [comment]
Hello,

In hvad, an object "does not exist" if it's not translated in the requested language. There are two ways to go around this:
* Always create the translation, even if it's left empty.
* Provide a list of language fallbacks using for instance `MyModel.objects.language().fallbacks("de", "fr", "en")`. You may also call `.fallbacks()` with no arguments to have it use `settings.LANGUAGES`.

Be aware that option 2 creates a self join on the translations table in the query. It's fine performance-wise thanks to rare matching entries, but it might affect `select_related` in odd ways, please check your results when using it.
