### ISSUE TITLE
Database test couldn't be flushed

### ISSUE THREAD

**Issue by fproldan** [KristianOellegaard/django-hvad#349]
Hello, I'm doing a few unittest and I'm getting the follow error:

```
CommandError: Database test_lms couldn't be flushed. Possible reasons:
  * The database isn't running or isn't configured correctly.
  * At least one of the expected database tables doesn't exist.
  * The SQL was invalid.
Hint: Look at the output of 'django-admin sqlflush'. That's the SQL this command wasn't able to run.
The full error: cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "trainingshared_componentsharedmultiplechoicequestion_translatio" references "trainingshared_componentsharedmultiplechoicequestion".
HINT:  Truncate table "trainingshared_componentsharedmultiplechoicequestion_translatio" at the same time, or use TRUNCATE ... CASCADE.

```

Any ideas?

Thanks

**Comment by spectras** [comment]
Hello,

Thanks for reporting here. I never had this, but I suspect it may come from some migration at some point.
Or, if you don't rebuild the test database from scratch (by DROPing it), there could be a constraint left over from tests from another version of either hvad or Django itself.

If at all possible, could you try dropping the whole test database and have it rebuilt, and see whether this still happens?

**Comment by spectras** [comment]
As there was no followup, I'll assume you managed to solve your issue. Please feel free to reopen as needed.
