### ISSUE TITLE
Something's wrong with your database installation. Make sure the appropriate database tables have been created, and make sure the database is readable by the appropriate user.

### ISSUE THREAD

**Issue by actongorton** [KristianOellegaard/django-hvad#350]
I've followed the installation instructions in the documentation, but when I try to access the model from the admin screen, I get the following error:

`Something's wrong with your database installation. Make sure the appropriate database tables have been created, and make sure the database is readable by the appropriate user.`

This doesn't give me anything to go on. The error does not occur with any other models, just the one being used with django-hvac.

Since this is for development, I've erased my migrations and created a fresh database, then migrated everything as a clean install. The error remains. 

Here are the python libraries I'm using in my project:
```
appdirs==1.4.3
boto3==1.7.10
botocore==1.10.10
brotlipy==0.7.0
cffi==1.11.5
Django==2.0.4
django-bakery==0.12.5
django-extensions==2.0.7
django-filter==1.1.0
django-hvad==1.8.0
django-polymorphic==2.0.2
djangorestframework==3.8.2
docutils==0.14
flake8==3.5.0
fs==2.0.20
jmespath==0.9.3
Markdown==2.6.11
mccabe==0.6.1
nece==0.7.5
psycopg2==2.7.4
psycopg2-binary==2.7.4
pycodestyle==2.4.0
pycparser==2.18
pyflakes==1.6.0
pygraphviz==1.3.1
python-dateutil==2.7.2
pytz==2018.4
s3transfer==0.1.13
six==1.11.0
```

**Comment by mapeal2** [comment]
Hi,

Same problem here, did you ever find the fix? 
I guess this has to do with the django version, you're using 2.0.4 and apparently it's not yet supported by hvad.

Regards.

**Comment by spectras** [comment]
As of now, django-hvad does not support Django2+.
I will work on this in the coming weeks, and will post updates on #344 .
Thanks for reporting here, and sorry for the delay.
