### ISSUE TITLE
(When) will the Django 2.x compatible beta be released?

### ISSUE THREAD

**Issue by maltebeckmann** [KristianOellegaard/django-hvad#362]
Hi!

I just ran into a modelform_factory() got an unexpected keyword argument 'change'. And I am only just waking up to the latest beta release going back to late 2018. I am running with django-parler but now that I have reintroduced django-cms to my project, I am not sure if I can do this without hvad.

Any news on this front?

**Comment by kcleong** [comment]
Please see this thread: https://github.com/KristianOellegaard/django-hvad/issues/344
