### ISSUE TITLE
Suggested feature: add support for select_related on TranslationAwareManager

### ISSUE THREAD

**Issue by dgerzo** [KristianOellegaard/django-hvad#71]
Hello, this isn't really an "issue", but more like a support question. I am posting here b/c you don't have a mailing list and IRC isn't very reliable support channel. So first, let me describe my models:

    class ModelA(TranslatableModel):
        code = CharField(max_length=3)

        translations = TranslatedFields(
            name = CharField(max_length=255)
        )

    class ModelB(Model):
        modela = ForeignKey(ModelA)

    class ModelC(Model):
        modelb = ForeignKey(ModelB)

My query looks like this:

    objs = get_translation_aware_manager(ModelC).language().select_related().filter(...)

However, when I iterate through the objs in my template and call obj.modelb.modela.name it makes an additional db query to get the translation, so I am facing the 1+n db queries, which doesn't really scale well.
Normally, when I call language() on TranslatableModel it prefetches translations for the given language, but it seems like the translations for related objects aren't prefetched. Would it be possible to do this kind of prefetching?

Thank you very much!

**Comment by spectras** [comment]
Closing this, as the issue will be moot in hvad2, since its querysets will be merged and the resulting queryset will support full `select_related`, including nested joins. Still a couple of months ahead, but there is not point working on it now.
